# Introducción {.unnumbered}

El presente estudio utilizará los datos de la encuesta del 2023 de la Encuesta Nacional de Hogares de Costa Rica(ENAHO). La ENAHO se lleva a cabo por el INEC (Instituto Nacional de Estadística y Censos de Costa Rica) y contiene datos detallados de más de 30.000 casos y aborda un total de 590 variables vinculadas a las condiciones socioeconómicas, demográficas y educativas de personas en Costa Rica. El estudio tiene como objetivo analizar el impacto del nivel educativo en la situación económica de las personas comprendidas entre los 18 y los 60 años. 
Dado los métodos utilizados en el análisis, el estudio será complejo y requerirá el uso de varias variables. Variables de identificación, como la región de planificación y la zona (urbana o rural). Varios análisis se llevarán a cabo para determinar las diferencias geográficas en la accesibilidad de la educación y cómo influyen en los niveles económicos. 
El estudio se centrará en las variables clave asociadas con la educación probación escolar, último año aprobado, tipo de centro educativo y se correlacionará con las medidas económicas como el ingreso, y la pobreza, entre otros, para evaluarse la relación entre la educación y la situación económica. Las variables como la condición de ocupado, desempleado y inactivo y los ingresos formarán la base del análisis para ver cómo el nivel educativo afecta la situación económica, pero también viceversa.
Se ha realizado una investigación bibliográfica relacionada con la educación y la pobreza, abarcando estudios previos en América Latina y específicamente en Costa Rica. Dichos estudios proporcionan un marco teórico y empírico sobre el examen de la relación entre educación y pobreza.
El propósito es explorar un análisis de datos basado en la evidencia para comprender mejor el impacto del nivel educativo sobre la condición socioeconómica en Costa Rica. 
