<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="es" xml:lang="es"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2&nbsp; Bitácora 2 – Bitácoras Grupo #1, CA-204 (II-2024)</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./bitacora-3.html" rel="next">
<link href="./bitacora-1.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Sin resultados",
    "search-matching-documents-text": "documentos encontrados",
    "search-copy-link-title": "Copiar el enlace en la búsqueda",
    "search-hide-matches-text": "Ocultar resultados adicionales",
    "search-more-match-text": "resultado adicional en este documento",
    "search-more-matches-text": "resultados adicionales en este documento",
    "search-clear-button-title": "Borrar",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancelar",
    "search-submit-button-title": "Enviar",
    "search-label": "Buscar"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./bitacora-2.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Bitácora 2</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Alternar barra lateral" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Buscar" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Bitácoras Grupo #1, CA-204 (II-2024)</a> 
        <div class="sidebar-tools-main">
    <div class="dropdown">
      <a href="" title="Descargar" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Descargar"><i class="bi bi-download"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Bitácoras-Grupo--1,-CA-204--II-2024-.pdf">
              <i class="bi bi-file-pdf pe-1"></i>
            Descargar PDF
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="./Bitácoras-Grupo--1,-CA-204--II-2024-.epub">
              <i class="bi bi-journal pe-1"></i>
            Descargar ePub
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Buscar"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introducción</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bitacora-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Bitácora 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bitacora-2.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Bitácora 2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bitacora-3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Bitácora 3</span></span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Tabla de contenidos</h2>
   
  <ul>
  <li><a href="#parte-de-planificación" id="toc-parte-de-planificación" class="nav-link active" data-scroll-target="#parte-de-planificación"><span class="header-section-number">2.1</span> Parte de planificación</a>
  <ul class="collapse">
  <li><a href="#ordenamiento-de-la-literatura" id="toc-ordenamiento-de-la-literatura" class="nav-link" data-scroll-target="#ordenamiento-de-la-literatura"><span class="header-section-number">2.1.1</span> Ordenamiento de la Literatura</a></li>
  </ul></li>
  <li><a href="#enlaces-de-la-literatura" id="toc-enlaces-de-la-literatura" class="nav-link" data-scroll-target="#enlaces-de-la-literatura"><span class="header-section-number">2.2</span> Enlaces de la literatura</a></li>
  <li><a href="#análisis-estadísticos" id="toc-análisis-estadísticos" class="nav-link" data-scroll-target="#análisis-estadísticos"><span class="header-section-number">2.3</span> Análisis estadísticos</a>
  <ul class="collapse">
  <li><a href="#análisis-descriptivo" id="toc-análisis-descriptivo" class="nav-link" data-scroll-target="#análisis-descriptivo"><span class="header-section-number">2.3.1</span> Análisis descriptivo</a></li>
  <li><a href="#construcción-de-fichas-de-resultados" id="toc-construcción-de-fichas-de-resultados" class="nav-link" data-scroll-target="#construcción-de-fichas-de-resultados"><span class="header-section-number">2.3.2</span> Construcción de fichas de resultados</a></li>
  <li><a href="#propuesta-metodológica" id="toc-propuesta-metodológica" class="nav-link" data-scroll-target="#propuesta-metodológica"><span class="header-section-number">2.3.3</span> Propuesta Metodológica</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Bitácora 2</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="parte-de-planificación" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="parte-de-planificación"><span class="header-section-number">2.1</span> Parte de planificación</h2>
<section id="ordenamiento-de-la-literatura" class="level3" data-number="2.1.1">
<h3 data-number="2.1.1" class="anchored" data-anchor-id="ordenamiento-de-la-literatura"><span class="header-section-number">2.1.1</span> Ordenamiento de la Literatura</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 3%">
<col style="width: 13%">
<col style="width: 29%">
<col style="width: 30%">
<col style="width: 2%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Organización</th>
<th></th>
<th></th>
<th>Literatura</th>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Tipo</strong></td>
<td><strong>Tema general</strong></td>
<td><strong>Tema específico</strong></td>
<td><strong>Título</strong></td>
<td><strong>Año</strong></td>
<td><strong>Autor(es)</strong></td>
</tr>
<tr class="even">
<td>Teórico</td>
<td>Capital humano y pobreza</td>
<td>Importancia del capital humano en la disminución de la pobreza</td>
<td>Human Capital and Poverty Alleviation</td>
<td>1995</td>
<td>Gary S. Becker</td>
</tr>
<tr class="odd">
<td>Teórico</td>
<td>Impacto de la educación en la pobreza</td>
<td>Cómo la educación secundaria y post-secundaria reduce la pobreza en Costa Rica</td>
<td>Evaluación de impacto de la educación sobre la pobreza en Costa Rica (un análisis para educación secundaria y postsecundaria)</td>
<td>2015</td>
<td>Carmen Sánchez</td>
</tr>
<tr class="even">
<td>Teórico</td>
<td>Impacto de la educación en la pobreza rural</td>
<td>Impacto de la educación primaria y secundaria en la reducción de la pobreza rural en México</td>
<td>Impacto de la educación en la pobreza rural</td>
<td>2009</td>
<td>Juan Luis Ordaz</td>
</tr>
<tr class="odd">
<td>Teórico</td>
<td>Impacto de la educación en la pobreza y la desigualdad</td>
<td>Impacto de la educación en la pobreza y la desigualdad en Costa Rica</td>
<td>Principales conclusiones del Libro: Educación, pobreza y desigualdad en Costa Rica</td>
<td>s.f.</td>
<td>Leonardo Sánchez y Rafael Arias</td>
</tr>
<tr class="even">
<td>Teórico</td>
<td>Impacto de la educación en la pobreza</td>
<td>Impacto de la educación en la pobreza multidimensional extrema y moderada en México</td>
<td>Las características de la educación y su efecto en la pobreza: un análisis para México</td>
<td>2024</td>
<td>Omar Ricárdez y David Robles</td>
</tr>
<tr class="odd">
<td>Teórico</td>
<td>Impacto de la pandemia en el sistema educativo</td>
<td>Cómo el rezago educativo producido por la pandemia podría afectar los niveles de pobreza y desigualdad en América Latina</td>
<td>The Impact of COVID-19 on Education in Latin America: Long-Run Implications for Poverty and Inequality</td>
<td>2024</td>
<td>Jessica Bracco, Matías Ciaschi, Leonardo Gasparini y Mariana Marchionni y Guido Neidhöfer</td>
</tr>
<tr class="even">
<td>Teórico</td>
<td>Relación entre educación y pobreza</td>
<td>Impacto de la pobreza en la educación y viceversa</td>
<td>Una aproximación empírica a la relación entre educación y pobreza</td>
<td>2007</td>
<td>Luis Fernando Aguado, Luis Eduardo Girón y Fernando Salazar</td>
</tr>
<tr class="odd">
<td>Teórico</td>
<td>Definición teórica de la pobreza</td>
<td>Definición de la pobreza desde una perspectiva estructural</td>
<td>Aspectos teóricos y metodológicos involucrados en el estudio de la pobreza: una revisión.</td>
<td>s.f.</td>
<td>Adrian Rodríguez</td>
</tr>
<tr class="even">
<td>Teórico</td>
<td>Relación entre educación, desigualdad y pobreza</td>
<td>Impacto de la educación en la pobreza y la desigualdad en México desde la teoría del capital humano y la teoría marxista</td>
<td>Educación y pobreza: una relación conflictiva</td>
<td>2001</td>
<td>Miguel Bazdresch</td>
</tr>
<tr class="odd">
<td>Teórico</td>
<td>Impacto de la educación en la pobreza</td>
<td>Impacto dela educación en la reducción de la pobreza multidimensional en Xinjiang, China.</td>
<td>Impact of Education on Multidimensional Poverty Reduction at thePost-Poverty Alleviation Era in Xinjiang</td>
<td>2023</td>
<td>Jian Qiu, Hongsen Wang y Ailida Aikerbayr</td>
</tr>
<tr class="even">
<td>Teórico</td>
<td>Impacto de la educación en la distribución del ingreso</td>
<td>Efecto de la educación en la nivelación de la distribución del ingreso en Perú</td>
<td>¿Mejora la distribución del ingreso con la educación?</td>
<td>2010</td>
<td>Adolfo Figueroa</td>
</tr>
<tr class="odd">
<td>Teórico</td>
<td>Desigualdad y pobreza</td>
<td>Efecto de los roles de género, la educación, la riqueza y la localización en la pobreza y la desigualdad en Ruanda</td>
<td>Decomposing inequality and poverty in post-war Rwanda: The roles of gender, education, wealth and location</td>
<td>2015</td>
<td>Kate Finnoff</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="enlaces-de-la-literatura" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="enlaces-de-la-literatura"><span class="header-section-number">2.2</span> Enlaces de la literatura</h2>
<p><span class="citation" data-cites="becker">(<a href="#ref-becker" role="doc-biblioref">Becker 1995</a>)</span>: <strong>Human Capital and Poverty Alleviation</strong></p>
<p>Resumen: El texto analiza cómo el capital humano, medido por la escolaridad y la expectativa de vida, es clave en el crecimiento económico, especialmente en países pobres. Afirma que una población más educada y saludable acelera el desarrollo, destacando la educación primaria y secundaria como motores principales. Además, se dice que la educación es esencial para reducir la desigualdad y mejorar la movilidad económica, al proporcionar herramientas para superar la vulnerabilidad.</p>
<p>Contraste: su base teórica se respalda en la teoría del capital humano, la cual establece que la educación, concebida como motor para el desarrollo de dicho capital, le permite a una persona tener los conocimientos y habilidades necesarias para aumentar su capacidad productiva, lo cual le conduce a ser más competitivo, ganar mejores ingresos y, en consecuencia, alcanzar una mejor calidad de vida. Dicha teoría respalda varios estudios que se abordarán en la presente investigación, como los de <span class="citation" data-cites="Sanchez">C. Sánchez (<a href="#ref-Sanchez" role="doc-biblioref">2015</a>)</span>, <span class="citation" data-cites="OrdazDiaz2009">Díaz (<a href="#ref-OrdazDiaz2009" role="doc-biblioref">2009</a>)</span>, y <span class="citation" data-cites="Hernandez">L. Sánchez y Arias (<a href="#ref-Hernandez" role="doc-biblioref">s.&nbsp;f.</a>)</span>.</p>
<p>Contribución propia: desde nuestra perspectiva, la teoría del capital humano resalta el vínculo entre educación y calidad de vida, lo cual destaca la necesidad de realizar estudios que analicen más a fondo dicha relación, en aras de tener un mayor fundamento para potencialmente invertir y proponer políticas dirigidas a mejorar el acceso a la educación.</p>
<p><span class="citation" data-cites="Sanchez">(<a href="#ref-Sanchez" role="doc-biblioref">C. Sánchez 2015</a>)</span>: <strong>Evaluación de impacto de la educación sobre la pobreza en Costa Rica (un análisis para educación secundaria y postsecundaria)</strong></p>
<p>Resumen: El estudio analiza la población de entre 25 y 60 años de la ENAHO 2013, dividiéndola entre quienes completaron secundaria y quienes alcanzaron niveles educativos superiores. Se evalúan características personales, de vivienda y del hogar para medir su correlación con el nivel educativo. Los resultados indican que completar la secundaria disminuye en un 5,7% la probabilidad de caer en la pobreza, mientras que obtener estudios postsecundarios la reduce en un 8,4%.</p>
<p>Contraste: el énfasis que se hace en la educación como motor para reducir la pobreza va en la misma línea que las ideas de <span class="citation" data-cites="becker">Becker (<a href="#ref-becker" role="doc-biblioref">1995</a>)</span> y el enfoque del capital humano. La investigación demuestra empíricamente la forma en que la educación secundaria y postsecundaria llegan a incidir en la condición socioeconómica de las personas, pero no se abarca el papel de la educación primaria a la cual alude <span class="citation" data-cites="becker">Becker (<a href="#ref-becker" role="doc-biblioref">1995</a>)</span>.</p>
<p>Contribución propia: Consideramos que es necesario explorar el mayor número de dimensiones que contribuyan a comprender el vínculo entre la educación y la condición socioeconómica de una persona, por lo cual resulta necesario encontrar información empírica a partir de los tres niveles educativos: educación primaria, secundaria y postsecundaria.</p>
<p><span class="citation" data-cites="OrdazDiaz2009">(<a href="#ref-OrdazDiaz2009" role="doc-biblioref">Díaz 2009</a>)</span>: <strong>Impacto de la educación en la pobreza rural</strong></p>
<p>Resumen: El estudio analiza el impacto de la educación primaria y secundaria en la reducción de la pobreza en zonas rurales de México, considerando tres niveles: pobreza alimentaria, de capacidades y de patrimonio. A nivel nacional, se encuentra que la educación primaria reduce la pobreza alimentaria, de capacidades y de patrimonio en un 18%, 16% y 4%, respectivamente, mientras que la secundaria lo hace en un 30%, 27% y 15%, mostrando un mayor impacto en la mejora de las condiciones de vida.</p>
<p>Contraste: esta fuente llega a la misma conclusión que las anteriores: la educación disminuye las probabilidades de caer en pobreza. En particular, este estudio hace la división entre tres niveles de pobreza, y cuantifica el impacto tanto de la educación primaria como secundaria en la reducción de estos, lo cual llena el vacío de conocimiento que se tenía con respecto a la influencia de la educación primaria.</p>
<p>Contribución propia: tener bien definido el concepto de pobreza y las dimensiones que esta involucra resulta imprescindible para poder llegar a conclusiones más precisas, pues, por ejemplo, no se puede decir que una familia que sólo no tenga acceso a internet tiene las mismas carencias que una familia que no tiene recursos para comer.</p>
<p><span class="citation" data-cites="Hernandez">(<a href="#ref-Hernandez" role="doc-biblioref">L. Sánchez y Arias, s.&nbsp;f.</a>)</span>: <strong>Principales conclusiones del Libro: Educación, pobreza y desigualdad en Costa Rica</strong></p>
<p>Resumen: El texto concluye que la educación es un factor clave para determinar la condición socioeconómica de una persona, ya que permite reducir necesidades básicas de albergue, higiene, conocimiento y consumo. Se afirma que los estudios universitarios mejoran las oportunidades de acceder al mercado laboral en condiciones favorables, disminuyendo así el riesgo de sufrir privación material.</p>
<p>Contraste: el estudio llega a conclusiones similares a las de <span class="citation" data-cites="becker">Becker (<a href="#ref-becker" role="doc-biblioref">1995</a>)</span> y <span class="citation" data-cites="Sanchez">C. Sánchez (<a href="#ref-Sanchez" role="doc-biblioref">2015</a>)</span>, en tanto está a favor de la educación como motor para alcanzar una mejor calidad de vida, y hasta llega a mostrar el impacto de la educación en otros indicadores de bienestar, como las necesidades de albergue, higiene, conocimiento y consumo.</p>
<p>Contribución propia: el mostrar el impacto de la educación en áreas ajenas al ingreso permite abordar la pobreza desde su perspectiva multidimensional, lo cual es esencial para que el estudio se apegue más fielmente a la realidad.</p>
<p><span class="citation" data-cites="ricardez">(<a href="#ref-ricardez" role="doc-biblioref">Ricárdez González y Robles Ortiz 2024</a>)</span>: <strong>Las características de la educación y su efecto en la pobreza: un análisis para México</strong></p>
<p>Resumen: se investiga el impacto de las 4 “A” de la educación—Accesibilidad, Aceptabilidad, Adaptabilidad y Disponibilidad—en la pobreza en México. Entre sus principales descubrimientos, se encuentra que una mayor accesibilidad educativa hacia las mujeres reduce su probabilidad de encontrarse en pobreza. Igualmente, se revela que, si se tienen profesores mejores capacitados y con salarios competitivos, o si se recibe una educación privada, se reduce también esta probabilidad.</p>
<p>Contraste: a pesar de llegar a la misma conclusión que los autores anteriores, este estudio llega a resultados más específicos, relacionando las variables principales de estudio con otras como el género y la calidad de la educación.</p>
<p>Contribución propia: incorporar un enfoque cualitativo a la investigación sobre educación y pobreza podría añadir valor al análisis, en tanto podría permitir llegar a conclusiones secundarias que detallen el panorama de la educación y precisen su impacto en la pobreza en Costa Rica.</p>
<p><span class="citation" data-cites="COVID">(<a href="#ref-COVID" role="doc-biblioref">Bracco et&nbsp;al. 2022</a>)</span>: <strong>The Impact of COVID-19 on Education in Latin America: Long-Run Implications for Poverty and Inequality</strong></p>
<p>Resumen: se habla sobre el impacto de la pandemia en los sistemas educativos en países latinoamericanos, y cómo dicho impacto podría determinar los niveles de pobreza y desigualdad en el futuro. Se encuentra que la interrupción en la formación de capital humano podría tener consecuencias negativas en los ingresos de las personas a largo plazo, y, en consecuencia, en los niveles de pobreza y desigualdad; se estima que la pobreza medida por nivel de ingreso podría incrementar de 8.4% a 20.7%.</p>
<p>Contraste: esta fuente sigue la línea de pensamiento de los autores anteriores de que el capital humano es un determinante de la condición económica de una persona, pero lo que la vuelve particular es que utiliza esta perspectiva para crear proyecciones a futuro sobre cómo la falta de educación podría afectar los niveles de pobreza.</p>
<p>Contribución propia: este tipo de perspectivas destacan la necesidad que tenemos de investigar sobre la relación entre la educación y la pobreza, pues muestran que a partir del conocimiento que construimos hoy sobre el ayer podemos tomar acciones a futuro con el potencial de mejorar el bienestar de la sociedad.</p>
<p><span class="citation" data-cites="Aguado">(<a href="#ref-Aguado" role="doc-biblioref">Aguado, Girón, y Salazar 2007</a>)</span>: <strong>Una aproximación empírica a la relación entre educación y pobreza</strong></p>
<p>Resumen: Se argumenta que la relación entre pobreza y educación se basa en una dinámica de reciprocidad, en donde la pobreza afecta a la educación y la educación a la pobreza. Se concluye que, si bien la educación es de los principales promotores de la movilidad económica, esta no garantiza que los individuos salgan de la pobreza, puesto que se necesitan de otros factores para generar un entorno económico favorable que permita mejorar la calidad de vida de las personas.</p>
<p>Contraste: Este estudio se respalda de la teoría del capital humano al igual que los demás autores, pero a la vez muestra sus limitaciones: se establece que se necesitan de condiciones favorables, ajenas a la educación, para mejorar la situación de un individuo, como las condiciones del mercado laboral.</p>
<p>Contribución propia: Esta investigación amplía el enfoque tradicional que vincula la educación con la pobreza, al incorporar una perspectiva integral que reconoce la necesidad de condiciones económicas favorables para que los beneficios de la educación puedan traducirse en mejoras de la condición socioeconómica de las personas.</p>
<p><span class="citation" data-cites="Rodriguez">(<a href="#ref-Rodriguez" role="doc-biblioref">Rodríguez, s.&nbsp;f.</a>)</span>: <strong>Aspectos teóricos y metodológicos involucrados en el estudio de la pobreza: una revisión</strong></p>
<p>Resumen: se revisan aspectos teóricos involucrados en estudiar la pobreza, entre los cuales destaca su enfoque estructural. Este consiste en que la pobreza es el resultado de estructuras económicas y sociales, entre las que se incluye a la educación, pero también al mercado de trabajo y cuestiones como la discriminación.</p>
<p>Contraste: este estudio ahonda en la multiplicidad de factores que determinan la pobreza, algunos de los cuales fueron sugeridos por <span class="citation" data-cites="Aguado">Aguado, Girón, y Salazar (<a href="#ref-Aguado" role="doc-biblioref">2007</a>)</span>. Esta fuente es diferente a aquellas que se sustentan en la teoría del capital humano, dado que va más allá de la educación, ofreciendo explicaciones diversas al fenómeno de la pobreza desde una perspectiva más social.</p>
<p>Contribución propia: es necesario reconocer las limitaciones de los sustentos teóricos que utilizamos para nuestra investigación, pues ello permite evaluar el alcance real de los resultados que se vayan a obtener, nos evita conclusiones simplistas y abre espacio para considerar variables no contempladas, fortaleciendo así la validez y rigor de la investigación.</p>
<p><span class="citation" data-cites="Bazdresch2001">(<a href="#ref-Bazdresch2001" role="doc-biblioref">Bazdresch Parada 2001</a>)</span>: <strong>Educación y pobreza: una relación conlictiva</strong></p>
<p>Resumen: se analizan diferentes estudios relacionados con la educación en México a lo largo del tiempo. Se introducen diferentes teorías sobre el efecto de la educación en la pobreza, entre las que destacan la del capital humano y la marxista (la cual dicta que la educación no puede resolver la pobreza por sí sola). Concluye que las personas pobres sufren de desigualdad de oportunidades, que les conducen a tener una educación de baja calidad que refuerza su estado de pobreza.</p>
<p>Contraste: esta fuente contrasta directamente con lo que postula la teoría del capital humano, en tanto afirma que la educación para las personas pobres bien puede existir, mas no es un medio efectivo para sacarlos de la pobreza. Estas ideas refuerzan la noción de <span class="citation" data-cites="Rodriguez">(<a href="#ref-Rodriguez" role="doc-biblioref">Rodríguez, s.&nbsp;f.</a>)</span> de que la pobreza puede ser producto de circunstancias sociales ajenas al entorno educativo.</p>
<p>Contribución propia: Esta investigación aporta al debate al integrar la teoría marxista con la noción de desigualdad estructural en México, mostrando cómo la educación, en su forma actual, no actúa como un mecanismo efectivo de movilidad social para las personas pobres. Empero, hay que tener presente que todo esto se hace en el caso particular de México, por lo que hay que tener presente que la situación en Costa Rica podría ser diferente.</p>
<p><span class="citation" data-cites="Jiang">(<a href="#ref-Jiang" role="doc-biblioref">Jiang Qiu y Aikerbayr 2023</a>)</span>: <strong>Impact of Education on Multidimensional Poverty Reduction at thePost-Poverty Alleviation Era in Xinjiang</strong></p>
<p>Resumen: se investiga el impacto de la educación secundaria en la probabilidad de sufrir pobreza multidimensional en Xinjiang, China. Existe una correlación negativa entre el nivel educativo y la pobreza medida a nivel individual. Empero, se encuentra que, para la población de menos de 35 años, esta correlación no es significativa, lo que se adjudica a la implementación de educación obligatoria general en años previos, lo cual, al disminuir la disparidad de acceso a la educación, permitiría a otros factores incidir más significativamente.</p>
<p>Contraste: al igual que <span class="citation" data-cites="Bazdresch2001">Bazdresch Parada (<a href="#ref-Bazdresch2001" role="doc-biblioref">2001</a>)</span>, se enfatiza que el entorno educativo puede ser poco significativo a la hora de determinar la condición de vida de una persona. Particularmente, se revela que una menor disparidad educativa permite vislumbrar mejor la influencia de otros factores, de manera que mayor igualdad de acceso a la educación podría conducir a una reducción en su influencia.</p>
<p>Contribución propia: a partir de los resultados de este estudio se podría inferir que, si bien el rol de la educación en la condición de vida de las personas puede ser minimizado, la implementación de políticas dirigidas a aumentar la igualdad de acceso a la educación podría contribuir a que el nivel educativo no influya en la condición socioeconómica de las personas; es decir, que por lo menos las personas con carencias no estén en esa situación por causa de la falta de escolaridad.</p>
<p><span class="citation" data-cites="figueroa">(<a href="#ref-figueroa" role="doc-biblioref">Figueroa 2010</a>)</span>: <strong>¿Mejora la distribución del ingreso con la educación?</strong></p>
<p>Resumen: se explica por qué la expansión educativa no se traduce directamente en una mayor igualdad del ingreso en Perú. Se concluye que la educación por sí sola no es suficiente para reducir la desigualdad del ingreso en economías con fuertes disparidades. Aunque la educación puede aumentar los ingresos individuales, no modifica la estructura económica subyacente, donde la concentración de activos y el poder de mercado perpetúan la desigualdad. Para que la educación tenga un impacto significativo en la distribución del ingreso, debe ser acompañada de políticas redistributivas que aborden las desigualdades estructurales en el acceso a recursos y oportunidades.</p>
<p>Contraste: Tanto <span class="citation" data-cites="figueroa">Figueroa (<a href="#ref-figueroa" role="doc-biblioref">2010</a>)</span> como <span class="citation" data-cites="Jiang">Jiang Qiu y Aikerbayr (<a href="#ref-Jiang" role="doc-biblioref">2023</a>)</span> y <span class="citation" data-cites="Bazdresch2001">Bazdresch Parada (<a href="#ref-Bazdresch2001" role="doc-biblioref">2001</a>)</span> coinciden en que la educación por sí sola no es suficiente para reducir la pobreza o la desigualdad. Asimismo, coinciden en que, incluso cuando la educación se expande, las desigualdades estructurales limitan su efectividad. Sin embargo, el enfoque de <span class="citation" data-cites="figueroa">Figueroa (<a href="#ref-figueroa" role="doc-biblioref">2010</a>)</span> es en la distribución del ingreso en lugar de la pobreza. Particularmente, propone explícitamente que la educación debe estar acompañada de políticas redistributivas que aborden la desigualdad en la concentración de activos.</p>
<p>Contribución propia: Aunque <span class="citation" data-cites="figueroa">Figueroa (<a href="#ref-figueroa" role="doc-biblioref">2010</a>)</span> acierta al destacar la necesidad de políticas redistributivas junto con la educación, es consideramos que podría ser importante ampliar su propuesta para incluir acceso a empleos de calidad y protección social. Una estrategia integral, que combine expansión educativa con otras políticas económicas, podría abordar más efectivamente las condiciones que perpetúan la desigualdad del ingreso.</p>
<p><span class="citation" data-cites="finnoff">(<a href="#ref-finnoff" role="doc-biblioref">Finnoff 2015</a>)</span>: <strong>Decomposing inequality and poverty in post-war Rwanda: The roles of gender, education, wealth and location</strong></p>
<p>Resumen: Se analizan las variables de pobreza y desigualdad en relación con factores como el hogar, la educación, la posesión de activos y la localización geográfica en Ruanda. En particular, se destaca que la educación del jefe del hogar actúa como un amortiguador frente a la pobreza, aunque su impacto es menor en comparación con otros factores, como la posesión de activos financieros y la localización geográfica. En cuanto a la distribución del ingreso, se concluye que en Ruanda la reforma agraria y la redistribución de activos tras la guerra civil tuvieron un papel más relevante que el desarrollo educativo.</p>
<p>Contraste: este estudio refuerza la idea de que la educación es solo uno de muchos factores que afectan a la pobreza y la desigualdad. Se alinea especialmente con las ideas de <span class="citation" data-cites="Bazdresch2001">Bazdresch Parada (<a href="#ref-Bazdresch2001" role="doc-biblioref">2001</a>)</span> y <span class="citation" data-cites="figueroa">Figueroa (<a href="#ref-figueroa" role="doc-biblioref">2010</a>)</span>, en tanto sugiere que, para que haya un impacto real, deben haber cambios estructurales en la economía.</p>
<p>Contribución propia: el análisis que se realiza en la situación de Ruanda es sumamente valioso para comprender los desafíos que enfrenta la educación para que llegue a tener un verdadero impacto en los países en vías de desarrollo. De manera aislada es muy difícil que la educación logre disminuir la pobreza y la desigualdad, por lo que es imprescindible que las reformas educativas vengan acompañadas de reformas estructurales para brindar mayor oportunidad a las personas que están en condición de pobreza y así el capital humano sea aprovechado de la mejor forma.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="análisis-estadísticos" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="análisis-estadísticos"><span class="header-section-number">2.3</span> Análisis estadísticos</h2>
<section id="análisis-descriptivo" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="análisis-descriptivo"><span class="header-section-number">2.3.1</span> Análisis descriptivo</h3>
<section id="formato-tidy" class="level4" data-number="2.3.1.1">
<h4 data-number="2.3.1.1" class="anchored" data-anchor-id="formato-tidy"><span class="header-section-number">2.3.1.1</span> Formato tidy</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 30,540
Columns: 58
$ REGION         &lt;fct&gt; Central, Central, Central, Central, Central, Central, C…
$ ZONA           &lt;fct&gt; Urbana, Urbana, Urbana, Urbana, Urbana, Urbana, Urbana,…
$ EFI            &lt;fct&gt; Bueno, Bueno, Regular, Regular, Regular, Regular, Regul…
$ CalViv         &lt;fct&gt; Óptima, Óptima, Aceptable, Aceptable, Aceptable, Acepta…
$ V19            &lt;fct&gt; No, No, SÍ, SÍ, SÍ, SÍ, No, No, No, SÍ, SÍ, SÍ, SÍ, SÍ,…
$ TamViv         &lt;dbl&gt; 2, 2, 4, 4, 4, 4, 3, 3, 3, 1, 1, 1, 1, 4, 4, 4, 4, 4, 4…
$ A3             &lt;fct&gt; "Jefe o jefa", "Hermano(a)", "Jefe o jefa", "Esposo(a) …
$ A4             &lt;fct&gt; Mujer, Mujer, Mujer, Hombre, Mujer, Mujer, Mujer, Mujer…
$ A5             &lt;dbl+lbl&gt; 80, 84, 51, 61, 29, 26, 50, 17, 16, 36, 25, 43, 70,…
$ A6             &lt;fct&gt; Viudo(a), Viudo(a), Casado(a), Casado(a), Soltero(a), S…
$ CondMig        &lt;fct&gt; Migrante interno, Migrante interno, Migrante externo, M…
$ A15A           &lt;fct&gt; Público, Público, Extranjero, Extranjero, Privado, Priv…
$ A15B           &lt;fct&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, UCR, UCR, N…
$ NivInst        &lt;fct&gt; Primaria completa, Primaria completa, Primaria completa…
$ Escolari       &lt;int&gt; 6, 6, 6, 6, 13, 14, 11, 10, 9, 16, 10, 17, 22, 11, 11, …
$ ForReg         &lt;fct&gt; NA, NA, NA, NA, "Ciencias", "Ciencias sociales, educaci…
$ A16B           &lt;fct&gt; NA, NA, NA, NA, "Profesorado o diplomado universitario"…
$ A17            &lt;fct&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ A20A           &lt;fct&gt; No, No, Sí, No, Sí, No, Sí, No, No, No, No, No, No, No,…
$ ForNoReg       &lt;fct&gt; NA, NA, "Ingeniería, industria y construcción", NA, "Ci…
$ A22A           &lt;fct&gt; No, No, No, Sí, Sí, Sí, No, Sí, Sí, Sí, No, Sí, Sí, No,…
$ itpn           &lt;dbl&gt; 433333, 541667, 500000, 151667, 488317, NA, 514454, NA,…
$ np             &lt;fct&gt; No pobre, No pobre, No pobre, No pobre, No pobre, No po…
$ IPM_Pobreza    &lt;fct&gt; No pobre multidimensional, No pobre multidimensional, N…
$ Q_IPCN         &lt;fct&gt; Q4: Más de ₡321.523 a ₡574.085, Q4: Más de ₡321.523 a ₡…
$ ipcn           &lt;dbl&gt; 487500, 487500, 456620, 456620, 456620, 456620, 205430,…
$ LugNac         &lt;fct&gt; "En otro cantón de residencia", "En otro cantón de resi…
$ A13            &lt;fct&gt; "No asiste", "No asiste", "No asiste", "No asiste", "No…
$ A14            &lt;fct&gt; Sexto primaria, Sexto primaria, Sexto primaria, Sexto p…
$ A18A           &lt;fct&gt; NA, NA, NA, NA, NA, NA, NA, No ha recibido ningún incen…
$ REZ_ESC        &lt;fct&gt; NA, NA, NA, NA, NA, NA, NA, Sin rezago, Sin rezago, NA,…
$ A18B           &lt;fct&gt; NA, NA, NA, NA, NA, NA, NA, No ha recibido segundo ince…
$ A18C           &lt;fct&gt; NA, NA, NA, NA, NA, NA, NA, No ha recibido tercer incen…
$ A21            &lt;fct&gt; NA, NA, "INA", NA, "Instituto privado (Jiménez, Boston,…
$ A22B           &lt;fct&gt; NA, NA, NA, Español, Inglés, Inglés, NA, Inglés, Inglés…
$ A23            &lt;fct&gt; Sí mantiene el hogar, Sí mantiene el hogar, Sí mantiene…
$ E1             &lt;fct&gt; NA, NA, NA, NA, Por tiempo indefinido o permanente, NA,…
$ IPM_Intensidad &lt;fct&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ ClasPubPrivPri &lt;fct&gt; NA, NA, NA, NA, Clasificado como privado, NA, Clasifica…
$ G3             &lt;fct&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ IPM_PS2        &lt;fct&gt; Sin la privación, Sin la privación, Sin la privación, S…
$ IPM_PS4        &lt;fct&gt; Sin la privación, Sin la privación, Con la privación, C…
$ Q_ZON_IPCN     &lt;fct&gt; 4, 4, 4, 4, 4, 4, 2, 2, 2, 5, 4, 5, 5, 2, 2, 2, 2, 3, 3…
$ Q_REG_IPCN     &lt;fct&gt; 4, 4, 4, 4, 4, 4, 2, 2, 2, 5, 4, 5, 5, 2, 2, 2, 2, 3, 3…
$ spmn           &lt;dbl&gt; NA, NA, NA, NA, 446650, NA, 339454, NA, NA, 625310, 312…
$ ipbh           &lt;dbl&gt; 0, 0, 704167, 704167, 704167, 704167, 494000, 494000, 4…
$ ipnh           &lt;dbl&gt; 0, 0, 634812, 634812, 634812, 634812, 441290, 441290, 4…
$ ithb           &lt;dbl&gt; 975000, 975000, 1895834, 1895834, 1895834, 1895834, 669…
$ ithn           &lt;dbl&gt; 975000, 975000, 1826479, 1826479, 1826479, 1826479, 616…
$ ipcb           &lt;dbl&gt; 487500, 487500, 473959, 473959, 473959, 473959, 223000,…
$ ipsnt          &lt;dbl&gt; NA, NA, NA, NA, 488317, NA, 339454, NA, NA, 683643, 312…
$ isanh          &lt;dbl&gt; NA, NA, 634812, 634812, 634812, 634812, 441290, 441290,…
$ ts             &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ ot             &lt;dbl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ ttmh           &lt;dbl&gt; 975000, 975000, 151667, 151667, 151667, 151667, 175000,…
$ tnmh           &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…
$ cba            &lt;dbl&gt; 62635, 62635, 62635, 62635, 62635, 62635, 62635, 62635,…
$ lp             &lt;dbl&gt; 129038, 129038, 129038, 129038, 129038, 129038, 129038,…</code></pre>
</div>
</div>
</section>
<section id="cuadros" class="level4" data-number="2.3.1.2">
<h4 data-number="2.3.1.2" class="anchored" data-anchor-id="cuadros"><span class="header-section-number">2.3.1.2</span> Cuadros</h4>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Distribución del nivel pobreza según universidad pública a la que asistió</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Universidad</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Pobreza extrema</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Pobreza no extrema</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">No pobre</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">UCR</td>
<td style="text-align: right;">0.52</td>
<td style="text-align: right;">2.41</td>
<td style="text-align: right;">46.3</td>
<td style="text-align: right;">49.3</td>
</tr>
<tr class="even">
<td style="text-align: left;">UNA</td>
<td style="text-align: right;">0.22</td>
<td style="text-align: right;">1.40</td>
<td style="text-align: right;">19.5</td>
<td style="text-align: right;">21.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">TEC</td>
<td style="text-align: right;">0.04</td>
<td style="text-align: right;">0.18</td>
<td style="text-align: right;">7.4</td>
<td style="text-align: right;">7.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">UNED</td>
<td style="text-align: right;">1.18</td>
<td style="text-align: right;">1.75</td>
<td style="text-align: right;">13.2</td>
<td style="text-align: right;">16.1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">UTN</td>
<td style="text-align: right;">0.26</td>
<td style="text-align: right;">0.61</td>
<td style="text-align: right;">5.0</td>
<td style="text-align: right;">5.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">2.23</td>
<td style="text-align: right;">6.35</td>
<td style="text-align: right;">91.4</td>
<td style="text-align: right;">100.0</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Fuente: </span> <sup></sup> INEC, Costa Rica. (2023). ENAHO, Julio 2023: Resultados Generales.</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tfoot>

</table>
</div>


</div>
</div>
<p>Esta tabla muestra la distribución de estudiantes en situación de pobreza, diferenciada entre extrema, no extrema y no pobre, según la universidad pública de Costa Rica a la que asistieron. La Universidad de Costa Rica (UCR) tiene la mayor proporción de estudiantes que no son pobres, representando el 46.3% de sus estudiantes, seguida por la Universidad Nacional (UNA) con un 19.5%. La Universidad Estatal a Distancia (UNED) y la Universidad Técnica Nacional (UTN) tienen una mayor proporción de estudiantes en pobreza extrema en comparación con las demás instituciones. Esta distribución sugiere que los estudiantes de la UCR y la UNA, en su mayoría, pertenecen a sectores con menor incidencia de pobreza en comparación con aquellos de la UNED y la UTN.</p>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Distribución de pobreza según quintiles de ingreso y dominio de segundo idioma</caption>
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="2" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Domina un segundo idioma
</div></th>
<th data-quarto-table-cell-role="th" style="text-align: right; empty-cells: hide; border-bottom: hidden;"></th>
</tr>
<tr class="odd">
<th style="text-align: left;" data-quarto-table-cell-role="th">Quintil</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">No</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Si</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">₡110.683 ó menos</td>
<td style="text-align: right;">21.26</td>
<td style="text-align: right;">0.55</td>
<td style="text-align: right;">21.80</td>
</tr>
<tr class="even">
<td style="text-align: left;">Más de ₡110.683 a ₡195.000</td>
<td style="text-align: right;">21.03</td>
<td style="text-align: right;">0.66</td>
<td style="text-align: right;">21.69</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Más de ₡195.000 a ₡321.523</td>
<td style="text-align: right;">19.41</td>
<td style="text-align: right;">1.54</td>
<td style="text-align: right;">20.95</td>
</tr>
<tr class="even">
<td style="text-align: left;">Más de ₡321.523 a ₡574.085</td>
<td style="text-align: right;">16.29</td>
<td style="text-align: right;">2.76</td>
<td style="text-align: right;">19.05</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Más de ₡574.085</td>
<td style="text-align: right;">10.77</td>
<td style="text-align: right;">5.73</td>
<td style="text-align: right;">16.51</td>
</tr>
<tr class="even">
<td style="text-align: left;">Total</td>
<td style="text-align: right;">88.77</td>
<td style="text-align: right;">11.23</td>
<td style="text-align: right;">100.00</td>
</tr>
</tbody><tfoot>
<tr class="even">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Fuente: </span> <sup></sup> INEC, Costa Rica. (2023). ENAHO, Julio 2023: Resultados Generales.</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tfoot>

</table>
</div>


</div>
</div>
<p>En esta tabla se presenta la relación entre los quintiles de ingreso, el nivel de pobreza y el dominio de un segundo idioma. Los estudiantes en el quintil más bajo (Q1) representan el 21.80% de la muestra total, con una proporción baja de personas que dominan un segundo idioma (0.55%). A medida que aumentan los ingresos (quintiles más altos), también aumenta el porcentaje de personas que dominan un segundo idioma. El quintil más alto (Q5) tiene la mayor proporción de personas que dominan un segundo idioma (5.73%), lo que sugiere una posible correlación entre mayores ingresos y la probabilidad de hablar un segundo idioma.</p>
<div class="cell">
<div class="cell-output-display">
<div class="table-responsive">
<table class="table table-striped table-hover caption-top table-sm small" data-quarto-postprocess="true">
<caption>Resumen del ingreso total por persona neto según nivel de instrucción</caption>
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Nivel de instrucción</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Media</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Promedio</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Desviación estándar</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Sin nivel de instrucción</td>
<td style="text-align: left;">₡99,333.00</td>
<td style="text-align: left;">₡162,827.70</td>
<td style="text-align: left;">₡183,642.73</td>
</tr>
<tr class="even">
<td style="text-align: left;">Primaria incompleta</td>
<td style="text-align: left;">₡108,333.00</td>
<td style="text-align: left;">₡165,109.09</td>
<td style="text-align: left;">₡189,822.21</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Primaria completa</td>
<td style="text-align: left;">₡232,168.50</td>
<td style="text-align: left;">₡271,151.18</td>
<td style="text-align: left;">₡275,476.39</td>
</tr>
<tr class="even">
<td style="text-align: left;">Secundaria académica incompleta</td>
<td style="text-align: left;">₡250,000.00</td>
<td style="text-align: left;">₡274,788.46</td>
<td style="text-align: left;">₡291,824.09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Secundaria académica completa</td>
<td style="text-align: left;">₡341,822.00</td>
<td style="text-align: left;">₡396,831.27</td>
<td style="text-align: left;">₡351,181.16</td>
</tr>
<tr class="even">
<td style="text-align: left;">Secundaria técnica incompleta</td>
<td style="text-align: left;">₡40,000.00</td>
<td style="text-align: left;">₡129,868.12</td>
<td style="text-align: left;">₡209,472.88</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Secundaria técnica completa</td>
<td style="text-align: left;">₡390,653.00</td>
<td style="text-align: left;">₡490,216.45</td>
<td style="text-align: left;">₡443,535.38</td>
</tr>
<tr class="even">
<td style="text-align: left;">Educación superior de pregrado y grado</td>
<td style="text-align: left;">₡650,000.00</td>
<td style="text-align: left;">₡820,016.63</td>
<td style="text-align: left;">₡773,662.39</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Educación superior de posgrado</td>
<td style="text-align: left;">₡1,302,975.00</td>
<td style="text-align: left;">₡1,548,859.68</td>
<td style="text-align: left;">₡1,084,856.26</td>
</tr>
</tbody><tfoot>
<tr class="even">
<td style="text-align: left; padding: 0;"><span style="font-style: italic;">Fuente: </span> <sup></sup> INEC, Costa Rica. (2023). ENAHO 2023, Julio 2023: Resultados Generales.</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tfoot>

</table>
</div>


</div>
</div>
<p>Esta tabla ofrece un resumen de los ingresos netos promedio por persona, clasificados según el nivel de instrucción alcanzado. Los niveles educativos superiores, como educación universitaria de posgrado, muestran un ingreso promedio significativamente mayor (₡1,548,859,68) en comparación con los niveles de educación básica o secundaria. La diferencia en el promedio de ingresos según el nivel educativo sugiere que a mayor nivel de instrucción, mayores son los ingresos netos promedio y menor es la desviación en los ingresos de los individuos.</p>
</section>
<section id="gráficos" class="level4" data-number="2.3.1.3">
<h4 data-number="2.3.1.3" class="anchored" data-anchor-id="gráficos"><span class="header-section-number">2.3.1.3</span> Gráficos</h4>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bitacora-2_files/figure-html/GRAFICO 1-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bitacora-2_files/figure-html/GRAFICO 2-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bitacora-2_files/figure-html/GRAFICO 3-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bitacora-2_files/figure-html/GRAFICO 4-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bitacora-2_files/figure-html/GRAFICO 5.1-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bitacora-2_files/figure-html/GRAFICO 5.2-1.png" class="img-fluid figure-img" width="1344"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bitacora-2_files/figure-html/GRAFICO 5.3-1.png" class="img-fluid figure-img" width="1344"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bitacora-2_files/figure-html/GRAFICO 6.1-1.png" class="img-fluid figure-img" width="1344"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bitacora-2_files/figure-html/GRAFICO 6.2-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bitacora-2_files/figure-html/GRAFICO 7-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bitacora-2_files/figure-html/GRAFICO 8-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bitacora-2_files/figure-html/GRAFICO 9-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bitacora-2_files/figure-html/GRAFICO 10-1.png" class="img-fluid figure-img" width="960"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bitacora-2_files/figure-html/GRAFICO 11.1-1.png" class="img-fluid figure-img" width="1104"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bitacora-2_files/figure-html/GRAFICO 11.2-1.png" class="img-fluid figure-img" width="1104"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bitacora-2_files/figure-html/GRAFICO 12-1.png" class="img-fluid figure-img" width="1104"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bitacora-2_files/figure-html/GRAFICO 13-1.png" class="img-fluid figure-img" width="1248"></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="bitacora-2_files/figure-html/GRAFICO 14-1.png" class="img-fluid figure-img" width="1536"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="construcción-de-fichas-de-resultados" class="level3" data-number="2.3.2">
<h3 data-number="2.3.2" class="anchored" data-anchor-id="construcción-de-fichas-de-resultados"><span class="header-section-number">2.3.2</span> Construcción de fichas de resultados</h3>
<p>Para la presente investigación se utilizarán las variables de la ENAHO del 2023 que estén vinculadas con las variables de estudio principales: educación, pobreza e ingreso. La base de datos abarca múltiples de estos parámetros, los cuales podrían ser útiles para responder la pregunta de investigación y, por ende, se toman en cuenta a la hora de hacer la selección de columnas que se procesarán del conjunto de datos. En las siguientes líneas, se analizarán aquellas que consideremos más relevantes en este momento, pero eso no significa que, a futuro, las observaciones no puedan contemplar más variables.</p>
<section id="hallazgo-1" class="level4" data-number="2.3.2.1">
<h4 data-number="2.3.2.1" class="anchored" data-anchor-id="hallazgo-1"><span class="header-section-number">2.3.2.1</span> Hallazgo 1</h4>
<ul>
<li>Nombre de su hallazgo/resultado: Altos ingresos netos del hogar respecto al nivel de instrucción</li>
<li>Resumen en una oración: Existen ciertos valores máximos respecto al ingreso neto del hogar que son inesperados.</li>
<li>Principal característica: Distribución de los valores extremos</li>
<li>Problemas o posibles desafíos: La distribución de los valores extremos no es uniforme entre los diferentes niveles de instrucción presentes en la base de datos.</li>
<li>Resumen en un párrafo: Al analizar el gráfico 12, se observa la distribución del ingreso neto del hogar según el nivel de instrucción de las personas encuestadas mediante un diagrama de cajas. Este gráfico muestra puntos aislados que se alejan de la media, tanto por debajo como por encima. Entre los máximos globales, destacan las categorías de Educación superior de postgrado, Educación superior de pregrado y grado, secundaria académica completa e incompleta. Las primeras dos categorías no presentan hallazgos sorprendentes, ya que es esperado que las personas con un alto nivel de instrucción tengan mayores ingresos. Sin embargo, los valores máximos en las categorías de secundaria académica completa e incompleta son inesperados, ya que sugieren que, en algunos casos, personas sin formación universitaria han logrado ingresar a los niveles más altos de ingresos netos del hogar dentro de la muestra encuestada. Esto plantea dudas sobre la creencia de que alcanzar un nivel universitario siempre garantiza un mayor ingreso a nivel doméstico.</li>
</ul>
</section>
<section id="hallazgo-2" class="level4" data-number="2.3.2.2">
<h4 data-number="2.3.2.2" class="anchored" data-anchor-id="hallazgo-2"><span class="header-section-number">2.3.2.2</span> Hallazgo 2</h4>
<ul>
<li>Nombre de su hallazgo/resultado: Pendiente de la regresión lineal de la relación años de escolaridad e ingreso salarial neto respecto al quintil de ingreso per cápita del hogar neto.</li>
<li>Resumen en una oración: La pendiente de la regresión aumenta a medida que se incrementa el quintil de ingreso per cápita del hogar neto.</li>
<li>Principal característica: Pendiente de la regresión lineal.</li>
<li>Problemas o posibles desafíos: La representatividad de la interpretación respecto a la población.</li>
<li>Resumen en un párrafo: En la gráfica 14, que relaciona los años de escolaridad con el ingreso principal de salario neto, se aprecia que, según el análisis de regresión lineal, la pendiente inicia en el quintil 1 con un valor cercano a cero, casi horizontal. La regresión lineal, permite evaluar cómo una variable independiente (en este caso, los años de escolaridad) impacta sobre una variable dependiente (el ingreso salarial). En este quintil, la pendiente sugiere que un cambio en los años de escolaridad no tiene un efecto significativo sobre el ingreso salarial. Es decir, para las personas de este quintil, tener un año más o menos de escolaridad no genera un impacto importante en su salario. Esta interpretación es clave para identificar qué segmentos de la población se benefician o no de incrementos en su nivel educativo.</li>
</ul>
</section>
<section id="hallazgo-3" class="level4" data-number="2.3.2.3">
<h4 data-number="2.3.2.3" class="anchored" data-anchor-id="hallazgo-3"><span class="header-section-number">2.3.2.3</span> Hallazgo 3</h4>
<ul>
<li>Nombre de su hallazgo/resultado: Personas estudiadas en universidades públicas por debajo de la línea de pobreza.</li>
<li>Resumen en una oración: Existe un grupo de estudiantes o exestudiantes de universidades públicas que, al momento de ser encuestados, se encontraban bajo la línea de pobreza.</li>
<li>Principal característica: Población por debajo de la línea de pobreza.</li>
<li>Problemas o posibles desafíos: No se tiene certeza de si esta muestra es suficientemente representativa como para extraer conclusiones definitivas sobre esta parte de la población.</li>
<li>Resumen en un párrafo: Al observar la gráfica 11.2, se nota que en las cinco universidades públicas se presenta una proporción de estudiantes o exestudiantes cuya situación económica se encuentra por debajo de la línea de pobreza. Aunque este porcentaje varía entre las universidades, es evidente que la UNED tiene la mayor proporción de personas en esta situación, mientras que el TEC muestra la menor. Este hallazgo abre la puerta a múltiples preguntas e hipótesis sobre posibles relaciones causales entre la educación universitaria y variables exógenas que influyen en la situación económica de los graduados. Aunque generalmente se asume que estudiar en una universidad brinda oportunidades de ascenso social, los resultados de esta gráfica muestran que un grupo de personas que han pasado por las aulas de universidades públicas aún se encuentra bajo la línea de pobreza, lo que cuestiona esta afirmación común.</li>
</ul>
</section>
<section id="hallazgo-4" class="level4" data-number="2.3.2.4">
<h4 data-number="2.3.2.4" class="anchored" data-anchor-id="hallazgo-4"><span class="header-section-number">2.3.2.4</span> Hallazgo 4</h4>
<ul>
<li>Nombre de su hallazgo/resultado: Estadísticas de ingreso total neto por persona según nivel de instrucción.</li>
<li>Resumen en una oración: Las personas con mayor nivel de instrucción presentan mayores cifras de ingreso total neto al momento de la encuesta.</li>
<li>Principal característica: Incremento notable en la mediana, el promedio y la desviación estándar del ingreso a medida que aumenta el nivel educativo.</li>
<li>Problemas o posibles desafíos: Las estadísticas de ingreso neto no son suficientes por sí solas para determinar el nivel socioeconómico de una persona.</li>
<li>Resumen en un párrafo: Al analizar la tabla 2.4, se pueden observar marcadas diferencias en el ingreso total por persona según el nivel de instrucción. Los datos reflejan que las personas con educación superior de posgrado tienen un ingreso promedio significativamente mayor, representando un incremento de más del 100% respecto a las personas sin ningún nivel de instrucción formal. Las cifras muestran cómo la mediana del ingreso se incrementa a medida que aumenta el nivel educativo. Por ejemplo, las personas con educación primaria completa tienen una mediana considerablemente superior a aquellas con educación primaria incompleta. Además, la desviación estándar crece de manera notable, particularmente en los niveles educativos superiores, lo que sugiere una mayor variabilidad en los ingresos en estos grupos. Este análisis refleja una clara relación entre el nivel de instrucción y el ingreso, aunque es importante considerar que el ingreso neto por sí solo no siempre captura de manera precisa el bienestar o el nivel socioeconómico general de una persona.</li>
</ul>
</section>
<section id="hallazgo-5" class="level4" data-number="2.3.2.5">
<h4 data-number="2.3.2.5" class="anchored" data-anchor-id="hallazgo-5"><span class="header-section-number">2.3.2.5</span> Hallazgo 5</h4>
<ul>
<li>Nombre de su hallazgo/resultado: Relevancia del manejo de un segundo idioma en el nivel de pobreza.</li>
<li>Resumen en una oración: No parece que dominar un segundo idioma tenga un impacto significativo en el nivel de pobreza de las personas encuestadas.</li>
<li>Principal característica: Independientemente del quintil de ingreso al que pertenezcan las personas, el porcentaje de aquellas que no dominan un segundo idioma supera el 80%.</li>
<li>Problemas o posibles desafíos: La educación en el manejo de un segundo idioma podría no tener un impacto relevante en la condición socioeconómica de las personas, al menos según la información proporcionada en la base de datos actual.</li>
<li>Resumen en un párrafo: Al observar los datos de la tabla 2.3, se puede notar que el dominio de un segundo idioma no parece ser un factor determinante para mejorar la situación de pobreza. De hecho, el porcentaje de personas que no dominan un segundo idioma se mantiene consistentemente alto en todos los quintiles, superando el 80% en total. Esto sugiere que la falta de habilidades en un segundo idioma no es una causa clara de pobreza, ya que la mayoría de las personas, independientemente de su nivel de ingreso, no dominan una segunda lengua. Además, los datos sugieren que la mejora en las condiciones socioeconómicas no está directamente vinculada a esta habilidad, lo que podría llevar a cuestionar si la enseñanza de un segundo idioma tiene el impacto esperado en el contexto de la pobreza.</li>
</ul>
<!-- Comentario del foro: De igual manera, podrían relacionarse los hallazgos, por ejemplo, el hallazgo 4 con el 1, aclarando que la generalización de los resultados en el hallazgo 4 es desmentida por el hallazgo 1, ya que no es cierto para todos los casos. -->
</section>
</section>
<section id="propuesta-metodológica" class="level3" data-number="2.3.3">
<h3 data-number="2.3.3" class="anchored" data-anchor-id="propuesta-metodológica"><span class="header-section-number">2.3.3</span> Propuesta Metodológica</h3>
<p>La metodología de esta investigación se basará en un análisis descriptivo de cuadros y gráficos para visualizar las relaciones entre las principales variables de estudio: educación, pobreza e ingreso. Se plantea abordar estas relaciones de las siguientes maneras:</p>
<p>En primer lugar, se generarán gráficos y cuadros que vinculen variables numéricas relacionadas con educación e ingreso, con el objetivo de crear regresiones lineales que ayuden a establecer una correlación visual entre estas dos variables. Por ejemplo, el gráfico 1 muestra la correlación entre los años de escolaridad y el ingreso.</p>
<p>En segundo lugar, los gráficos 1 y 2 presentan otro enfoque, que consiste en analizar las relaciones entre variables considerando características como la región o zona. Este enfoque podría ofrecer observaciones más precisas sobre distintos segmentos de la población, y podría ampliarse en el futuro para incluir otras características como el género, la condición de migrante o el estado civil.</p>
<p>Finalmente, se crearán elementos visuales que permitan observar la distribución de características de interés en relación con las variables principales. Por ejemplo, los gráficos 3 y 4 muestran la distribución de la pobreza en función del nivel educativo, el gráfico 5.2 refleja la distribución de títulos educativos según los quintiles de ingreso per cápita, y el gráfico 11.2 ilustra la distribución del ingreso según la universidad pública a la que se asistió.</p>
<p>A partir de lo establecido anteriormente, se considera que los cálculos estadísticos que mejor se podrían aplicar son los relacionados con la media, desviación estándar, cuantiles y proporciones. Estos cálculos permitirán obtener una visión clara de las tendencias generales en los datos (media), la variabilidad de las observaciones (desviación estándar), así como una comprensión más detallada de la distribución de los valores a través de los cuantiles. Las proporciones, por su parte, facilitarán el análisis de categorías específicas como los niveles de pobreza y educación, ayudando a identificar patrones importantes dentro del grupo de estudio. Estos indicadores serán cruciales para comparar diferencias entre subgrupos y realizar inferencias sobre la relación entre educación, ingreso y pobreza.</p>
<p>A continuación, se presenta el código para la creación de gráficos y cuadros que se ha desarrollado hasta el momento:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="do">#############</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># GRAFICO 1 #</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="do">#############</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Grafico de ingreso total personal neto por años de escolaridad segun zona</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>datos_jc <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Escolari, <span class="at">y =</span> itpn, <span class="at">group =</span> ZONA)) <span class="sc">+</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hex</span>(<span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span> </span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">colour =</span> <span class="st">"red"</span>) <span class="sc">+</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>ZONA) <span class="sc">+</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Gráfico 1. </span><span class="sc">\n</span><span class="st">Relación entre años de escolaridad e ingreso personal neto"</span>,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Distribución del ingreso según zona urbana y rural en Costa Rica"</span>,</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Escolaridad"</span>,</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Ingreso"</span>,</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Fuente: Instituto Nacional de Estadística y Censos (INEC), Costa Rica. (2023). Encuesta Nacional de Hogares 2023, Julio 2023: Resultados Generales."</span>)<span class="sc">+</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>(<span class="at">labels =</span> <span class="fu">label_number</span>()) <span class="sc">+</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>  cowplot<span class="sc">::</span><span class="fu">theme_cowplot</span>() <span class="sc">+</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">6</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="do">#############</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># GRAFICO 2 #</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="do">#############</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Grafico de ingreso total personal neto por años de escolaridad segun region de planificacion </span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>datos_jc<span class="sc">$</span>REGION <span class="ot">&lt;-</span> <span class="fu">as_factor</span>(datos_jc<span class="sc">$</span>REGION) </span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>datos_jc <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Escolari, <span class="at">y =</span> itpn, <span class="at">group =</span> REGION, <span class="at">colour =</span> REGION)) <span class="sc">+</span></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> </span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">colour =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span>REGION) <span class="sc">+</span></span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Gráfico 2. </span><span class="sc">\n</span><span class="st">Relación entre escolaridad e ingreso personal neto según región de planificación"</span>,</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Comparativa de ingresos por años de escolaridad en las distintas regiones de planificación de Costa Rica"</span>,</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Escolaridad"</span>,</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Ingreso"</span>,</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Fuente: Instituto Nacional de Estadística y Censos (INEC), Costa Rica. (2023). Encuesta Nacional de Hogares 2023, Julio 2023: Resultados Generales."</span>)<span class="sc">+</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>(<span class="at">labels =</span> <span class="fu">label_number</span>()) <span class="sc">+</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>  cowplot<span class="sc">::</span><span class="fu">theme_cowplot</span>() <span class="sc">+</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">6</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="do">#############</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co"># GRAFICO 3 #</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="do">#############</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Grafico de pobreza segun nivel de instrucción</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>datos_jc <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(np)) <span class="sc">%&gt;%</span> </span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> np, <span class="at">fill =</span> NivInst)) <span class="sc">+</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Grafico 3. </span><span class="sc">\n</span><span class="st">Distribución de la Pobreza según Nivel de Instrucción en Costa Rica"</span>,</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Comparación entre Pobreza Extrema, Pobreza No Extrema y No Pobreza según el Nivel Educativo"</span>,</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Nivel de pobreza"</span>,</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="cn">NULL</span>, <span class="co"># Eliminar el título del eje y</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Nivel de instrucción"</span>,</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Fuente: Instituto Nacional de Estadística y Censos (INEC), Costa Rica. (2023). Encuesta Nacional de Hogares 2023, Julio 2023: Resultados Generales."</span>)<span class="sc">+</span>  </span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"GnBu"</span>) <span class="sc">+</span>  <span class="co"># Paleta de colores </span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>  cowplot<span class="sc">::</span><span class="fu">theme_cowplot</span>() <span class="sc">+</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>),</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>),</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">6</span>, <span class="at">hjust =</span> <span class="dv">0</span>))  <span class="co"># Cambiar el tamaño del texto del eje x</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="do">#############</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># GRAFICO 4 #</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="do">#############</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Grafico de pobreza multidimensional segun nivel de instruccion</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>datos_jc <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(IPM_Pobreza)) <span class="sc">%&gt;%</span> </span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> IPM_Pobreza, <span class="at">fill =</span> NivInst)) <span class="sc">+</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Gráfico 4. </span><span class="sc">\n</span><span class="st">Distribución de la Pobreza Multidimensional según Nivel de Instrucción en Costa Rica"</span>,</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Comparación entre Pobreza Multidimensional y No Pobreza Multidimensional por Nivel Educativo en 2023"</span>,</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Nivel de pobreza"</span>,</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="cn">NULL</span>, <span class="co"># Eliminar el título del eje y</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Nivel de instrucción"</span>,</span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Fuente: Instituto Nacional de Estadística y Censos (INEC), Costa Rica. (2023). Encuesta Nacional de Hogares 2023, Julio 2023: Resultados Generales."</span>)<span class="sc">+</span>  </span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Greens"</span>) <span class="sc">+</span>  <span class="co"># Paleta de colores </span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  cowplot<span class="sc">::</span><span class="fu">theme_cowplot</span>() <span class="sc">+</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>),</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>),</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">6</span>, <span class="at">hjust =</span> <span class="dv">0</span>))  <span class="co"># Cambiar el tamaño del texto del eje x</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="do">#############</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># GRAFICO 5.1 #</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="do">#############</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Numero de titulos obtenidos segun quintil de ingreso per capita</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>datos_jc <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(A16B)) <span class="sc">%&gt;%</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Q_IPCN, <span class="at">fill =</span> A16B)) <span class="sc">+</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span>  <span class="co"># Colocar barras separadas dentro de cada cuartil</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Gráfico 5.1. </span><span class="sc">\n</span><span class="st">Distribución de Títulos Obtenidos según Quintil de Ingreso Per Cápita en Costa Rica"</span>,</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Cantidad de títulos obtenidos en cada nivel educativo, clasificados por quintiles de ingreso per cápita al 2023"</span>,</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="cn">NULL</span>,  <span class="co"># Eliminar el título del eje x</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="cn">NULL</span>,  <span class="co"># Eliminar el título del eje y</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Título obtenido"</span>,</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Fuente: Instituto Nacional de Estadística y Censos (INEC), Costa Rica. (2023). Encuesta Nacional de Hogares 2023, Julio 2023: Resultados Generales."</span>)<span class="sc">+</span>  <span class="co"># Título de la leyenda</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_polar</span>() <span class="sc">+</span>  <span class="co"># Gráfico circular</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>() <span class="sc">+</span>  <span class="co"># Aplicar la transformación de raíz cuadrada a la escala de y</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Set3"</span>) <span class="sc">+</span>  <span class="co"># Paleta de colores </span></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>  cowplot<span class="sc">::</span><span class="fu">theme_cowplot</span>() <span class="sc">+</span></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>),  <span class="co"># Tamaño de texto de la leyenda</span></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>, <span class="at">hjust =</span> <span class="dv">5</span>),</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">6</span>, <span class="at">hjust =</span> <span class="dv">0</span>))  <span class="co"># Tamaño del texto en el eje x</span></span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="do">#############</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># GRAFICO 5.2 #</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="do">#############</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>ENAHO <span class="sc">%&gt;%</span> </span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(A16B) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(Q_IPCN) <span class="sc">&amp;</span> A16B <span class="sc">!=</span> <span class="st">"Ignorado"</span>) <span class="sc">%&gt;%</span>  <span class="co"># Filtrar valores NA</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(A16B, Q_IPCN) <span class="sc">%&gt;%</span>  <span class="co"># Agrupar por título y quintil</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">conteo =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span>  <span class="co"># Contar el número de personas en cada grupo</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> Q_IPCN, <span class="at">values_from =</span> conteo, <span class="at">values_fill =</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span> <span class="co">#view() # Convertir a formato ancho</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggparcoord</span>(<span class="at">columns =</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">groupColumn =</span> <span class="dv">1</span>, <span class="at">scale =</span> <span class="st">"uniminmax"</span>) <span class="sc">+</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Gráfico 5.2. </span><span class="sc">\n</span><span class="st">Distribución de títulos académicos obtenidos por quintil de ingreso per cápita Costa Rica, 2023"</span>,</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>         <span class="at">subtitle =</span> <span class="st">"Relación entre nivel educativo y nivel de ingreso per cápita según quintiles de ingresos"</span>,</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>         <span class="at">x =</span> <span class="st">"Quintil de ingreso per cápita"</span>,</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>         <span class="at">y =</span> <span class="cn">NULL</span>,</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>         <span class="at">caption =</span> <span class="st">"Fuente: Instituto Nacional de Estadística y Censos (INEC), Costa Rica. (2023). Encuesta Nacional de Hogares 2023, Julio 2023: Resultados Generales."</span>) <span class="sc">+</span></span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_color_discrete</span>(<span class="at">name =</span> <span class="st">"Título"</span>) <span class="sc">+</span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">scale_x_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Q1: 110683 ó menos"</span> <span class="ot">=</span> <span class="st">"1"</span>, </span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Q2: Más de 110683 a 195000"</span> <span class="ot">=</span> <span class="st">"2"</span>, </span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Q3: Más de 195000 a 321523"</span> <span class="ot">=</span> <span class="st">"3"</span>, </span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Q4: Más de 321523 a 574085"</span> <span class="ot">=</span> <span class="st">"4"</span>, </span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Q5: Más de 574085"</span> <span class="ot">=</span> <span class="st">"5"</span>)) <span class="sc">+</span></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>    cowplot<span class="sc">::</span><span class="fu">theme_cowplot</span>() <span class="sc">+</span></span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>    <span class="fu">theme</span>(<span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>),</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>          <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">6</span>, <span class="at">hjust =</span> <span class="dv">0</span>),</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>          <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">20</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="do">#############</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># GRAFICO 5.3 #</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="do">#############</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>ENAHO <span class="sc">%&gt;%</span> </span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(A16B) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(Q_IPCN) <span class="sc">&amp;</span> A16B <span class="sc">!=</span> <span class="st">"Ignorado"</span>) <span class="sc">%&gt;%</span>  <span class="co"># Filtrar valores NA</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(A16B, Q_IPCN) <span class="sc">%&gt;%</span>  <span class="co"># Agrupar por título y quintil</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">conteo =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span>  <span class="co"># Contar el número de personas en cada grupo</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> Q_IPCN, <span class="at">values_from =</span> conteo, <span class="at">values_fill =</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span> <span class="co">#view() # Convertir a formato ancho</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggparcoord</span>(<span class="at">columns =</span> <span class="dv">2</span><span class="sc">:</span><span class="dv">6</span>, <span class="at">groupColumn =</span> <span class="dv">1</span>, <span class="at">scale =</span> <span class="st">"globalminmax"</span>) <span class="sc">+</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Gráfico 5.3. </span><span class="sc">\n</span><span class="st">Número de títulos académicos obtenidos por quintil de ingreso per cápita Costa Rica, 2023"</span>,</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Comparación de la cantidad de títulos académicos obtenidos según quintiles de ingreso per cápita"</span>,</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Quintil de ingreso per cápita"</span>,</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Cantidad de títulos obtenidos"</span>,</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Fuente: Instituto Nacional de Estadística y Censos (INEC), Costa Rica. (2023). Encuesta Nacional de Hogares 2023, Julio 2023: Resultados Generales."</span>) <span class="sc">+</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_discrete</span>(<span class="at">name =</span> <span class="st">"Título"</span>) <span class="sc">+</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_discrete</span>(<span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Q1: 110683 ó menos"</span> <span class="ot">=</span> <span class="st">"1"</span>, </span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Q2: Más de 110683 a 195000"</span> <span class="ot">=</span> <span class="st">"2"</span>, </span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Q3: Más de 195000 a 321523"</span> <span class="ot">=</span> <span class="st">"3"</span>, </span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Q4: Más de 321523 a 574085"</span> <span class="ot">=</span> <span class="st">"4"</span>, </span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>                              <span class="st">"Q5: Más de 574085"</span> <span class="ot">=</span> <span class="st">"5"</span>)) <span class="sc">+</span></span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>  cowplot<span class="sc">::</span><span class="fu">theme_cowplot</span>() <span class="sc">+</span></span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>),</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">6</span>, <span class="at">hjust =</span> <span class="dv">0</span>),</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">20</span>, <span class="at">hjust =</span> <span class="dv">1</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="do">#############</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># GRAFICO 6.1 #</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="do">#############</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Grafico de distribucion del ingreso segun dominio de un segundo idioma</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>datos_jc <span class="sc">%&gt;%</span> </span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> A22A, <span class="at">y =</span> itpn, <span class="at">fill =</span> A22A)) <span class="sc">+</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span>  <span class="co"># Omitir valores extremos</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">129038</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span>  <span class="co"># Línea horizontal</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">0.5</span>, <span class="at">y =</span> <span class="dv">150000</span>, <span class="at">label =</span> <span class="st">"Línea de pobreza"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">hjust =</span> <span class="dv">0</span>) <span class="sc">+</span>  <span class="co"># Texto</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>(<span class="at">labels =</span> scales<span class="sc">::</span>comma) <span class="sc">+</span>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#f7a072"</span>, <span class="st">"#0fa3b1"</span>)) <span class="sc">+</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Gráfico 6.1. </span><span class="sc">\n</span><span class="st">Distribución del ingreso total neto por persona según el dominio de un segundo idioma en Costa Rica"</span>,</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Comparación entre personas que dominan y no dominan un segundo idioma al 2023"</span>,</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Dominio de un segundo idioma"</span>,</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Ingreso total personal neto"</span>,</span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Fuente: Instituto Nacional de Estadística y Censos (INEC), Costa Rica. (2023). Encuesta Nacional de Hogares 2023, Julio 2023: Resultados Generales."</span>)<span class="sc">+</span></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>  cowplot<span class="sc">::</span><span class="fu">theme_cowplot</span>() <span class="sc">+</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">6</span>, <span class="at">hjust =</span> <span class="dv">0</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="do">#############</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># GRAFICO 6.2 #</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="do">#############</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>datos_jc <span class="sc">%&gt;%</span> </span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> A22A, <span class="at">y =</span> itpn, <span class="at">fill =</span> A22A)) <span class="sc">+</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>(<span class="at">outlier.shape =</span> <span class="cn">NA</span>) <span class="sc">+</span>  <span class="co"># Omitir valores extremos</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">129038</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span>  <span class="co"># Línea horizontal</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">0.5</span>, <span class="at">y =</span> <span class="dv">150000</span>, <span class="at">label =</span> <span class="st">"Línea de pobreza"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">hjust =</span> <span class="dv">0</span>) <span class="sc">+</span>  <span class="co"># Texto</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>(<span class="at">labels =</span> scales<span class="sc">::</span>comma) <span class="sc">+</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"#22577a"</span>, <span class="st">"#57cc99"</span>)) <span class="sc">+</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Gráfico 6.2. </span><span class="sc">\n</span><span class="st">Distribución del ingreso total personal neto según dominio de un segundo idioma en Costa Rica"</span>,</span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Comparación de la distribución de ingresos entre personas que dominan o no un segundo idioma en 2023"</span>,</span>
<span id="cb10-14"><a href="#cb10-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Dominio de un segundo idioma"</span>,</span>
<span id="cb10-15"><a href="#cb10-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Ingreso total personal neto"</span>,</span>
<span id="cb10-16"><a href="#cb10-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Fuente: Instituto Nacional de Estadística y Censos (INEC), Costa Rica. (2023). Encuesta Nacional de Hogares 2023, Julio 2023: Resultados Generales."</span>)<span class="sc">+</span></span>
<span id="cb10-17"><a href="#cb10-17" aria-hidden="true" tabindex="-1"></a>  cowplot<span class="sc">::</span><span class="fu">theme_cowplot</span>() <span class="sc">+</span></span>
<span id="cb10-18"><a href="#cb10-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb10-19"><a href="#cb10-19" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">6</span>, <span class="at">hjust =</span> <span class="dv">0</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="do">#############</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co"># GRAFICO 7 #</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="do">#############</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Grafico de ingreso segun formacion educativa forma</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>ENAHO <span class="sc">%&gt;%</span> </span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(ForReg) <span class="sc">&amp;</span> itpn <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">&amp;</span> ForReg <span class="sc">!=</span> <span class="st">"Ignorada"</span> <span class="sc">&amp;</span> ForReg <span class="sc">!=</span> <span class="st">"No definida"</span>) <span class="sc">%&gt;%</span>  <span class="co"># Filtrar valores NA y menores o iguales a 0</span></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> itpn, <span class="at">y =</span> ForReg, <span class="at">fill =</span> ForReg, <span class="at">color =</span> ForReg)) <span class="sc">+</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density_ridges</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">129038</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span>  <span class="co"># Línea horizontal</span></span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">y =</span> <span class="fl">0.7</span>, <span class="at">x =</span> <span class="dv">150000</span>, <span class="at">label =</span> <span class="st">"Línea de pobreza"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">hjust =</span> <span class="dv">0</span>) <span class="sc">+</span>  <span class="co"># Texto</span></span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Gráfico 7. </span><span class="sc">\n</span><span class="st">Distribución del ingreso total personal neto según formación educativa en Costa Rica"</span>,</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Comparación entre los niveles de formación educativa y el ingreso en 2023"</span>,</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Ingreso"</span>,</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Formación educativa"</span>,</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Fuente: Instituto Nacional de Estadística y Censos (INEC), Costa Rica. (2023). Encuesta Nacional de Hogares 2023, Julio 2023: Resultados Generales."</span>)<span class="sc">+</span></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>(<span class="at">labels =</span> scales<span class="sc">::</span>comma) <span class="sc">+</span>  <span class="co"># Mostrar en millones</span></span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Dark2"</span>) <span class="sc">+</span>  <span class="co"># Paleta cualitativa ordinal</span></span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_brewer</span>(<span class="at">palette =</span> <span class="st">"Dark2"</span>) <span class="sc">+</span>  <span class="co"># Paleta cualitativa ordinal</span></span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>  cowplot<span class="sc">::</span><span class="fu">theme_cowplot</span>() <span class="sc">+</span></span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>, <span class="at">angle =</span> <span class="dv">25</span>, <span class="at">hjust =</span> <span class="dv">1</span>),</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">6</span>, <span class="at">hjust =</span> <span class="dv">0</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="do">#############</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># GRAFICO 8 #</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="do">#############</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Graficos de porcentaje de pobreza segun si se tiene secundaria o primaria completa</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>datos_jc <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(np))<span class="sc">%&gt;%</span> </span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Tiene_prim_completa, <span class="at">fill =</span> np)) <span class="sc">+</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Gráfico 8. </span><span class="sc">\n</span><span class="st">Distribución de la Pobreza Multidimensional por Nivel de Educación en Costa Rica"</span>,</span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Análisis comparativo entre pobrezas según la completitud de primaria en 2023."</span>,</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Porcentaje"</span>,</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Nivel de pobreza"</span>,</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Fuente: Instituto Nacional de Estadística y Censos (INEC), Costa Rica. (2023). Encuesta Nacional de Hogares 2023, Julio 2023: Resultados Generales."</span>)<span class="sc">+</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"OrRd"</span>) <span class="sc">+</span>  <span class="co"># Paleta de colores </span></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>  cowplot<span class="sc">::</span><span class="fu">theme_cowplot</span>() <span class="sc">+</span></span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">6</span>, <span class="at">hjust =</span> <span class="dv">0</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="do">#############</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># GRAFICO 9 #</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="do">#############</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>datos_jc <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(np))<span class="sc">%&gt;%</span> </span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Tiene_sec_completa, <span class="at">fill =</span> np)) <span class="sc">+</span></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Gráfico 9. </span><span class="sc">\n</span><span class="st">Distribución de la Pobreza según Nivel de Educación Secundaria en Costa Rica"</span>,</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Comparación del porcentaje de pobreza extrema, pobreza no extrema y no pobreza según la finalización de la educación secundaria, 2023."</span>,</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Porcentaje"</span>,</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Nivel de pobreza"</span>,</span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Fuente: Instituto Nacional de Estadística y Censos (INEC), Costa Rica. (2023). Encuesta Nacional de Hogares 2023, Julio 2023: Resultados Generales."</span>)<span class="sc">+</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"YlOrBr"</span>) <span class="sc">+</span>  <span class="co"># Paleta de colores </span></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>  cowplot<span class="sc">::</span><span class="fu">theme_cowplot</span>() <span class="sc">+</span></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">10</span>),</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">6</span>, <span class="at">hjust =</span> <span class="dv">0</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="do">##############</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co"># GRAFICO 10 #</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="do">##############</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>datos_jc <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(np))<span class="sc">%&gt;%</span> </span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Tiene_est_postsec, <span class="at">fill =</span> np)) <span class="sc">+</span></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">position =</span> <span class="st">"fill"</span>) <span class="sc">+</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Gráfico 10. </span><span class="sc">\n</span><span class="st">Distribución de la Pobreza según Nivel de Educación Postsecundaria en Costa Rica"</span>,</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Comparación del porcentaje de pobreza extrema, pobreza no extrema y no pobreza según la finalización de estudios postsecundarios, 2023."</span>,</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="cn">NULL</span>,</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Porcentaje"</span>,</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Nivel de pobreza"</span>,</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Fuente: Instituto Nacional de Estadística y Censos (INEC), Costa Rica. (2023). Encuesta Nacional de Hogares 2023, Julio 2023: Resultados Generales."</span>)<span class="sc">+</span></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Purples"</span>) <span class="sc">+</span>  <span class="co"># Paleta de colores </span></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>  cowplot<span class="sc">::</span><span class="fu">theme_cowplot</span>() <span class="sc">+</span></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">9</span>),</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">6</span>, <span class="at">hjust =</span> <span class="dv">0</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="do">##############</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="co"># GRAFICO 11.1 #</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="do">##############</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co">#Grafico de distribucion de ingreso por universidad publica</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a>datos_jc <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(A15B) <span class="sc">&amp;</span> A15B <span class="sc">!=</span> <span class="st">"Ignorado"</span>)<span class="sc">%&gt;%</span> </span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> A15B, <span class="at">y =</span> itpn, <span class="at">fill =</span> A15B)) <span class="sc">+</span></span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_violin</span>() <span class="sc">+</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">129038</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span>  <span class="co"># Línea horizontal</span></span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> <span class="fl">1.15</span>, <span class="at">y =</span> <span class="dv">150000</span>, <span class="at">label =</span> <span class="st">"Línea de pobreza"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">hjust =</span> <span class="dv">0</span>) <span class="sc">+</span>  <span class="co"># Texto</span></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Gráfico 11.1 </span><span class="sc">\n</span><span class="st">Distribución del Ingreso Neto Total por Persona según Universidad Pública en Costa Rica"</span>,</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Comparación del ingreso total por persona neto entre egresados de universidades públicas, considerando la línea de pobreza en 2023."</span>,</span>
<span id="cb15-14"><a href="#cb15-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Universidad"</span>,</span>
<span id="cb15-15"><a href="#cb15-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Ingreso total por persona neto"</span>,</span>
<span id="cb15-16"><a href="#cb15-16" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Fuente: Instituto Nacional de Estadística y Censos (INEC), Costa Rica. (2023). Encuesta Nacional de Hogares 2023, Julio 2023: Resultados Generales."</span>)<span class="sc">+</span></span>
<span id="cb15-17"><a href="#cb15-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>(<span class="at">labels =</span> scales<span class="sc">::</span>comma) <span class="sc">+</span></span>
<span id="cb15-18"><a href="#cb15-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Set1"</span>) <span class="sc">+</span>  <span class="co"># Paleta de colores</span></span>
<span id="cb15-19"><a href="#cb15-19" aria-hidden="true" tabindex="-1"></a>  cowplot<span class="sc">::</span><span class="fu">theme_cowplot</span>() <span class="sc">+</span></span>
<span id="cb15-20"><a href="#cb15-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb15-21"><a href="#cb15-21" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>, <span class="at">angle =</span> <span class="dv">25</span>, <span class="at">hjust =</span> <span class="dv">1</span>),</span>
<span id="cb15-22"><a href="#cb15-22" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">6</span>, <span class="at">hjust =</span> <span class="dv">0</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="do">##############</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="co"># GRAFICO 11.2 #</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a><span class="do">##############</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>datos_jc <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(A15B) <span class="sc">&amp;</span> A15B <span class="sc">!=</span> <span class="st">"Ignorado"</span> <span class="sc">&amp;</span> itpn <span class="sc">&gt;</span> <span class="dv">0</span>)<span class="sc">%&gt;%</span> </span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> itpn, <span class="at">y =</span> A15B, <span class="at">fill =</span> A15B)) <span class="sc">+</span></span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density_ridges</span>() <span class="sc">+</span></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">129038</span>, <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span>  <span class="co"># Línea horizontal</span></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">y =</span> <span class="fl">0.7</span>, <span class="at">x =</span> <span class="dv">150000</span>, <span class="at">label =</span> <span class="st">"Línea de pobreza"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">size =</span> <span class="dv">2</span>, <span class="at">hjust =</span> <span class="dv">0</span>) <span class="sc">+</span>  <span class="co"># Texto</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Gráfico 11.2. </span><span class="sc">\n</span><span class="st">Distribución del Ingreso Neto Total por Persona según Universidad Pública en Costa Rica"</span>,</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">subtitle =</span> <span class="st">"Comparación del ingreso total por persona neto entre egresados de universidades públicas, considerando la línea de pobreza en 2023."</span>,</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Universidad"</span>,</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Ingreso total por persona neto"</span>,</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Fuente: Instituto Nacional de Estadística y Censos (INEC), Costa Rica. (2023). Encuesta Nacional de Hogares 2023, Julio 2023: Resultados Generales."</span>)<span class="sc">+</span></span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Set1"</span>) <span class="sc">+</span>  <span class="co"># Paleta de colores</span></span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_log10</span>(<span class="at">labels =</span> scales<span class="sc">::</span>comma) <span class="sc">+</span></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>  cowplot<span class="sc">::</span><span class="fu">theme_cowplot</span>() <span class="sc">+</span></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>,</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>        <span class="at">axis.text.y =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">8</span>, <span class="at">angle =</span> <span class="dv">25</span>, <span class="at">hjust =</span> <span class="dv">1</span>),</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>        <span class="at">plot.caption =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">6</span>, <span class="at">hjust =</span> <span class="dv">0</span>))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="do">##############</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># GRAFICO 12 #</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="do">##############</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>variables_comunes <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> NivInst,</span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>                                <span class="at">y =</span> ipnh,</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>                                <span class="at">fill =</span> NivInst)) <span class="sc">+</span></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">scale_y_log10</span>(<span class="at">labels =</span> <span class="fu">label_number</span>()) <span class="sc">+</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">labs</span>( <span class="at">title =</span> <span class="st">"Gráfico 12. </span><span class="sc">\n</span><span class="st">Comparación del Ingreso Principal Neto del Hogar según Nivel de Instrucción, en Costa Rica al 2023"</span>,</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>                           <span class="at">subtitle =</span> <span class="st">"Expresado en colones costarricenses"</span>,</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>                           <span class="at">x =</span> <span class="st">"Nivel de Instrucción"</span>,</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>                           <span class="at">y =</span> <span class="st">"Ingreso Principal Neto del Hogar"</span>,</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>                           <span class="at">fill =</span>  <span class="st">"Nivel de Instrucción"</span>,</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>                           <span class="at">caption =</span> <span class="st">"Fuente: Instituto Nacional de Estadística y Censos (INEC), Costa Rica. (2023). Encuesta Nacional de Hogares 2023, Julio 2023: Resultados Generales."</span>) <span class="sc">+</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">coord_flip</span>() <span class="sc">+</span> </span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"none"</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="do">##############</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="co"># GRAFICO 13 #</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="do">##############</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>variables_comunes <span class="sc">%&gt;%</span> <span class="fu">filter</span>(spmn <span class="sc">&gt;</span> <span class="dv">0</span> <span class="sc">&amp;!</span><span class="fu">is.na</span>(A16B)) <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> spmn, </span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>                                                     <span class="at">y =</span> A16B, </span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>                                                     <span class="at">fill =</span> A16B, </span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>                                                     <span class="at">color =</span> A16B)) <span class="sc">+</span> </span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">geom_density_ridges</span>(<span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span> </span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">scale_x_log10</span>(<span class="at">labels =</span> <span class="fu">label_number</span>()) <span class="sc">+</span></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">labs</span>( <span class="at">title =</span> <span class="st">"Figura 13. </span><span class="sc">\n</span><span class="st">Distribución del Ingreso Total por persona del Hogar según Grado Académico en Costa Rica, 2023"</span>,</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>                            <span class="at">subtitle =</span> <span class="st">"Expresado en colones costarricenses"</span>,</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>                            <span class="at">x =</span> <span class="st">"Ingreso total del hogar neto"</span>,</span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>                            <span class="at">y =</span> <span class="st">"Título"</span>,</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a>                            <span class="at">fill =</span> <span class="st">"Título"</span>,</span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>                            <span class="at">color =</span> <span class="st">"Título"</span>,</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>                            <span class="at">caption =</span> <span class="st">"Fuente: Instituto Nacional de Estadística y Censos (INEC), Costa Rica. (2023). Encuesta Nacional de Hogares 2023, Julio 2023: Resultados Generales."</span>) <span class="sc">+</span></span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">guides</span>(</span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>                        <span class="at">fill =</span> <span class="fu">guide_legend</span>(<span class="at">reverse =</span> <span class="cn">TRUE</span>),  </span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a>                        <span class="at">color =</span> <span class="fu">guide_legend</span>(<span class="at">reverse =</span> <span class="cn">TRUE</span>)) <span class="sc">+</span> </span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">theme</span>(<span class="at">axis.text.y =</span> <span class="fu">element_blank</span>())</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="do">##############</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="co"># GRAFICO 14 #</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="do">##############</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>variables_comunes <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Q_IPCN)) <span class="sc">%&gt;%</span> </span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>                     <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Escolari, </span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>                                <span class="at">y =</span> ipsnt, </span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>                                <span class="at">colour =</span> Q_IPCN)) <span class="sc">+</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">geom_jitter</span>() <span class="sc">+</span></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">colour =</span> <span class="st">"black"</span>) <span class="sc">+</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a>                      <span class="fu">facet_wrap</span>(<span class="sc">~</span>Q_IPCN) <span class="sc">+</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Figura 14. </span><span class="sc">\n</span><span class="st">Relación entre los años de escolaridad e ingreso salario neto"</span>,</span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Años de escolaridad"</span>,</span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Ingreso principal salario neto total"</span>,</span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>       <span class="at">colour =</span> <span class="st">"Quintiles de ingreso per cápita </span><span class="sc">\n</span><span class="st">del hogar neto </span><span class="sc">\n</span><span class="st">por región de planificación"</span>,</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a>       <span class="at">caption =</span> <span class="st">"Fuente: Instituto Nacional de Estadística y Censos (INEC), Costa Rica. (2023). Encuesta Nacional de Hogares 2023, Julio 2023: Resultados Generales."</span>) <span class="sc">+</span></span>
<span id="cb19-16"><a href="#cb19-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_log10</span>(<span class="at">labels =</span> <span class="fu">label_number</span>()) <span class="sc">+</span></span>
<span id="cb19-17"><a href="#cb19-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_colour_brewer</span>(<span class="at">palette =</span> <span class="st">"Set1"</span>) <span class="sc">+</span>  <span class="co"># Paleta de colores para los quintiles</span></span>
<span id="cb19-18"><a href="#cb19-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_cowplot</span>()</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="do">###############</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   TABLA 1   #</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="do">###############</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>tabla1 <span class="ot">&lt;-</span> variables_comunes <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(A15B) <span class="sc">&amp;</span> A15B <span class="sc">!=</span> <span class="st">'Ignorado'</span>) <span class="sc">%&gt;%</span> <span class="fu">select</span>(A15B,np)</span>
<span id="cb20-6"><a href="#cb20-6" aria-hidden="true" tabindex="-1"></a>tabla1 <span class="ot">&lt;-</span> tabla1 <span class="sc">%&gt;%</span></span>
<span id="cb20-7"><a href="#cb20-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(A15B, np) <span class="sc">%&gt;%</span></span>
<span id="cb20-8"><a href="#cb20-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> np, </span>
<span id="cb20-9"><a href="#cb20-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">values_from =</span> n, </span>
<span id="cb20-10"><a href="#cb20-10" aria-hidden="true" tabindex="-1"></a>              <span class="at">values_fill =</span> <span class="dv">0</span>)</span>
<span id="cb20-11"><a href="#cb20-11" aria-hidden="true" tabindex="-1"></a>tabla1 <span class="ot">&lt;-</span> tabla1 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>( <span class="at">Total =</span> <span class="st">`</span><span class="at">Pobreza extrema</span><span class="st">`</span><span class="sc">+</span><span class="st">`</span><span class="at">Pobreza no extrema</span><span class="st">`</span><span class="sc">+</span> <span class="st">`</span><span class="at">No pobre</span><span class="st">`</span>)</span>
<span id="cb20-12"><a href="#cb20-12" aria-hidden="true" tabindex="-1"></a>tabla1 <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>( tabla1, tabla1 <span class="sc">%&gt;%</span> <span class="fu">summarise</span>( <span class="at">A15B =</span> <span class="st">"Total"</span>,</span>
<span id="cb20-13"><a href="#cb20-13" aria-hidden="true" tabindex="-1"></a>                                                   <span class="st">`</span><span class="at">Pobreza extrema</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">sum</span>(<span class="st">`</span><span class="at">Pobreza extrema</span><span class="st">`</span>),</span>
<span id="cb20-14"><a href="#cb20-14" aria-hidden="true" tabindex="-1"></a>                                                   <span class="st">`</span><span class="at">Pobreza no extrema</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">sum</span>(<span class="st">`</span><span class="at">Pobreza no extrema</span><span class="st">`</span>),</span>
<span id="cb20-15"><a href="#cb20-15" aria-hidden="true" tabindex="-1"></a>                                                   <span class="st">`</span><span class="at">No pobre</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">sum</span>(<span class="st">`</span><span class="at">No pobre</span><span class="st">`</span>),</span>
<span id="cb20-16"><a href="#cb20-16" aria-hidden="true" tabindex="-1"></a>                                                   <span class="at">Total =</span> <span class="fu">sum</span>(Total)))</span>
<span id="cb20-17"><a href="#cb20-17" aria-hidden="true" tabindex="-1"></a>tabla1 <span class="ot">&lt;-</span> tabla1 <span class="sc">%&gt;%</span></span>
<span id="cb20-18"><a href="#cb20-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), </span>
<span id="cb20-19"><a href="#cb20-19" aria-hidden="true" tabindex="-1"></a>                <span class="sc">~</span> <span class="fu">percent</span>(. <span class="sc">/</span><span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(variables_comunes<span class="sc">$</span>A15B) <span class="sc">&amp;</span> variables_comunes<span class="sc">$</span>A15B <span class="sc">!=</span> <span class="st">'Ignorado'</span>))))</span>
<span id="cb20-20"><a href="#cb20-20" aria-hidden="true" tabindex="-1"></a>tabla1 <span class="ot">&lt;-</span> tabla1 <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">Universidad =</span> A15B)</span>
<span id="cb20-21"><a href="#cb20-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-22"><a href="#cb20-22" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(tabla1, <span class="at">caption =</span> <span class="st">"Tabla 1: </span><span class="sc">\n</span><span class="st">Distribución de la pobreza según universidades"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb20-23"><a href="#cb20-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kable_styling</span>(<span class="at">position =</span> <span class="st">"center"</span>, <span class="at">bootstrap_options =</span> <span class="fu">c</span>(<span class="st">"striped"</span>, <span class="st">"hover"</span>, <span class="st">"responsive"</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb20-24"><a href="#cb20-24" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_header_above</span>(<span class="fu">c</span>(<span class="st">" "</span> <span class="ot">=</span> <span class="dv">1</span>, <span class="st">"Distribución de la pobreza"</span> <span class="ot">=</span> <span class="dv">4</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb20-25"><a href="#cb20-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">footnote</span>(<span class="at">general =</span> <span class="st">"Fuente: Instituto Nacional de Estadística y Censos (INEC), Costa Rica. (2023). Encuesta Nacional de Hogares 2023, Julio 2023: Resultados Generales."</span>)</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="do">###############</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   TABLA 2   #</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="do">###############</span></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>tabla2 <span class="ot">&lt;-</span> variables_comunes <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Q_IPCN) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(A22A)) <span class="sc">%&gt;%</span> <span class="fu">select</span>(Q_IPCN,A22A)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>tabla2 <span class="ot">&lt;-</span> tabla2 <span class="sc">%&gt;%</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(Q_IPCN, A22A) <span class="sc">%&gt;%</span></span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> A22A, </span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>              <span class="at">values_from =</span> n, </span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>              <span class="at">values_fill =</span> <span class="dv">0</span>)</span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>tabla2 <span class="ot">&lt;-</span> tabla2 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>( <span class="at">Total =</span> <span class="st">`</span><span class="at">Sí</span><span class="st">`</span><span class="sc">+</span><span class="st">`</span><span class="at">No</span><span class="st">`</span> )</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a>tabla2 <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>( tabla2, tabla2 <span class="sc">%&gt;%</span> <span class="fu">summarise</span>( <span class="at">Q_IPCN =</span> <span class="st">"Total"</span>,</span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a>                                                   <span class="st">`</span><span class="at">Sí</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">sum</span>(<span class="st">`</span><span class="at">Sí</span><span class="st">`</span>),</span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a>                                                   <span class="st">`</span><span class="at">No</span><span class="st">`</span> <span class="ot">=</span> <span class="fu">sum</span>(<span class="st">`</span><span class="at">No</span><span class="st">`</span>),</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a>                                                   <span class="at">Total =</span> <span class="fu">sum</span>(Total)))</span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a>tabla2 <span class="ot">&lt;-</span> tabla2 <span class="sc">%&gt;%</span></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), </span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>                <span class="sc">~</span> <span class="fu">percent</span>(. <span class="sc">/</span><span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(variables_comunes<span class="sc">$</span>Q_IPCN) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(variables_comunes<span class="sc">$</span>A22A)))))</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>tabla2 <span class="ot">&lt;-</span> tabla2 <span class="sc">%&gt;%</span> <span class="fu">rename</span>(<span class="at">Quintil =</span> Q_IPCN,</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'Domina un segundo idioma'</span> <span class="ot">=</span> Sí,</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>                            <span class="st">'No domina un segundo idioma'</span> <span class="ot">=</span> No</span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>                            )</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="do">###############</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   TABLA 3   #</span></span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="do">###############</span></span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>tabla3 <span class="ot">&lt;-</span> variables_comunes <span class="sc">%&gt;%</span> <span class="fu">filter</span>(NivInst <span class="sc">!=</span> <span class="st">'Ignorado'</span> <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(itpn) <span class="sc">&amp;</span> itpn <span class="sc">!=</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb22-6"><a href="#cb22-6" aria-hidden="true" tabindex="-1"></a>                                <span class="fu">select</span>(NivInst,itpn) <span class="sc">%&gt;%</span> </span>
<span id="cb22-7"><a href="#cb22-7" aria-hidden="true" tabindex="-1"></a>                                <span class="fu">group_by</span>(NivInst) <span class="sc">%&gt;%</span> </span>
<span id="cb22-8"><a href="#cb22-8" aria-hidden="true" tabindex="-1"></a>                                <span class="fu">summarize</span>(<span class="at">Media =</span> <span class="fu">median</span>(itpn, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb22-9"><a href="#cb22-9" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">Promedio =</span> <span class="fu">mean</span>(itpn, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb22-10"><a href="#cb22-10" aria-hidden="true" tabindex="-1"></a>                                          Desviación <span class="ot">=</span> <span class="fu">sd</span>(itpn, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb22-11"><a href="#cb22-11" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">Min =</span> <span class="fu">min</span>(itpn, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb22-12"><a href="#cb22-12" aria-hidden="true" tabindex="-1"></a>                                          <span class="at">Max =</span> <span class="fu">max</span>(itpn, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb22-13"><a href="#cb22-13" aria-hidden="true" tabindex="-1"></a>                                <span class="fu">rename</span>(<span class="st">'Nivel de instrucción'</span> <span class="ot">=</span> NivInst)</span>
<span id="cb22-14"><a href="#cb22-14" aria-hidden="true" tabindex="-1"></a>tabla3 <span class="ot">&lt;-</span> tabla3 <span class="sc">%&gt;%</span></span>
<span id="cb22-15"><a href="#cb22-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), </span>
<span id="cb22-16"><a href="#cb22-16" aria-hidden="true" tabindex="-1"></a>                <span class="sc">~</span> <span class="fu">number</span>(., <span class="at">big.mark =</span> <span class="st">"."</span>, <span class="at">decimal.mark =</span> <span class="st">","</span>, <span class="at">accuracy =</span> <span class="fl">0.01</span>, <span class="at">prefix =</span> <span class="st">"₡"</span>)))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="do">###############</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a><span class="co">#   TABLA 4   #</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="do">###############</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>tabla4 <span class="ot">&lt;-</span> variables_comunes <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Q_IPCN) <span class="sc">&amp;</span> <span class="sc">!</span><span class="fu">is.na</span>(ipcn) <span class="sc">&amp;</span> ipcn <span class="sc">!=</span> <span class="dv">0</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(Q_IPCN,ipcn) <span class="sc">%&gt;%</span> </span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Q_IPCN) <span class="sc">%&gt;%</span> </span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">Media =</span> <span class="fu">median</span>(ipcn, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a>            <span class="at">Promedio =</span> <span class="fu">mean</span>(ipcn, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a>            Desviación <span class="ot">=</span> <span class="fu">sd</span>(ipcn, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="st">'Quintil'</span> <span class="ot">=</span> Q_IPCN)</span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a>tabla4 <span class="ot">&lt;-</span> tabla4 <span class="sc">%&gt;%</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), </span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a>                <span class="sc">~</span> <span class="fu">number</span>(., <span class="at">big.mark =</span> <span class="st">"."</span>, <span class="at">decimal.mark =</span> <span class="st">","</span>, <span class="at">accuracy =</span> <span class="fl">0.01</span>, <span class="at">prefix =</span> <span class="st">"₡"</span>)))</span></code><button title="Copiar al portapapeles" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-Aguado" class="csl-entry" role="listitem">
Aguado, Luis, Luis Girón, y Fernando Salazar. 2007. <span>«Una aproximación empírica a la relación entre educación y pobreza»</span>. <em>Problemas del Desarrollo. Revista Latinoamericana de Economía</em>. <a href="https://www.redalyc.org/articulo.oa?id=11820124003 ">https://www.redalyc.org/articulo.oa?id=11820124003 </a>.
</div>
<div id="ref-Bazdresch2001" class="csl-entry" role="listitem">
Bazdresch Parada, Miguel. 2001. <span>«Educación y pobreza: una relación conflictiva»</span>. En <em>Pobreza, desigualdad social y ciudadanía. Los límites de las políticas sociales en América Latina</em>. Buenos Aires: CLACSO, Consejo Latinoamericano de Ciencias Sociales. <a href="chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://biblioteca.clacso.edu.ar/clacso/gt/20101029064158/6ziccardi.pdf">chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://biblioteca.clacso.edu.ar/clacso/gt/20101029064158/6ziccardi.pdf</a>.
</div>
<div id="ref-becker" class="csl-entry" role="listitem">
Becker, Gary. 1995. <span>«Human <span>Capital</span> and <span>Poverty</span> <span>Alleviation</span>»</span> 1. <a href="https://documentos.bancomundial.org/es/publication/documents-reports/documentdetail/121791468764735830/human-capital-and-poverty-alleviation">https://documentos.bancomundial.org/es/publication/documents-reports/documentdetail/121791468764735830/human-capital-and-poverty-alleviation</a>.
</div>
<div id="ref-COVID" class="csl-entry" role="listitem">
Bracco, Jessica, Matías Ciaschi, Leonardo Gasparini, Mariana Marchionni, y Guido Neidhöfer. 2022. <span>«The <span>Impact</span> of <span>COVID</span>-19 on <span>Education</span> in <span>Latin</span> <span>America</span> : <span>Long</span>-<span>Run</span> <span>Implications</span> for <span>Poverty</span> and <span>Inequality</span>»</span>. <em>World Bank Group</em> 1. <a href="https://doi.org/10.1596/1813-9450-10259">https://doi.org/10.1596/1813-9450-10259</a>.
</div>
<div id="ref-OrdazDiaz2009" class="csl-entry" role="listitem">
Díaz, Juan Luis Ordaz. 2009. <em>México: Impacto de la Educación en la Pobreza Rural</em>. Estudios y perspectivas, Sede Subregional de la CEPAL en México, No. 105. México, D. F.: Naciones Unidas. <a href="https://repositorio.cepal.org/bitstream/handle/11362/5377/S0901052.pdf">https://repositorio.cepal.org/bitstream/handle/11362/5377/S0901052.pdf</a>.
</div>
<div id="ref-figueroa" class="csl-entry" role="listitem">
Figueroa, Adolfo. 2010. <span>«¿<span>Mejora</span> la distribución del ingreso con la educación? <span>El</span> caso del <span>Perú</span>.»</span> <em>Revista de la CEPAL</em>, n.º 102 (diciembre): 115-36. <a href="https://research.proxyucr.elogim.com/linkprocessor/plink?id=4a799d99-4855-3d4f-ba4b-c6e5f649b0ad">https://research.proxyucr.elogim.com/linkprocessor/plink?id=4a799d99-4855-3d4f-ba4b-c6e5f649b0ad</a>.
</div>
<div id="ref-finnoff" class="csl-entry" role="listitem">
Finnoff, Kade. 2015. <span>«Decomposing inequality and poverty in post-war <span>Rwanda</span>: <span>The</span> roles of gender, education, wealth and location.»</span> <em>Development Southern Africa</em> 32 (2): 209-28. <a href="https://doi.org/10.1080/0376835X.2014.984375">https://doi.org/10.1080/0376835X.2014.984375</a>.
</div>
<div id="ref-Jiang" class="csl-entry" role="listitem">
Jiang Qiu, Hongsen Wang, y Ailida Aikerbayr. 2023. <span>«Impact of <span>Education</span> on <span>Multidimensional</span> <span>Poverty</span> <span>Reduction</span> at the <span>Post</span>-<span>Poverty</span> <span>Alleviation</span> <span>Era</span> in <span>Xinjiang</span>.»</span> <em>East Asian Economic Review</em> 27 (3): 243-69. <a href="https://doi.org/10.11644/KIEP.EAER.2023.27.3.424">https://doi.org/10.11644/KIEP.EAER.2023.27.3.424</a>.
</div>
<div id="ref-ricardez" class="csl-entry" role="listitem">
Ricárdez González, Omar, y David Robles Ortiz. 2024. <span>«Las características de la educación y su efecto en la pobreza: un análisis para <span>México</span>.»</span> <em>Análisis Económico</em> 39 (101): 165-79. <a href="https://doi.org/10.24275/uam/azc/dcsh/ae/2024v39n101/Ricardez">https://doi.org/10.24275/uam/azc/dcsh/ae/2024v39n101/Ricardez</a>.
</div>
<div id="ref-Rodriguez" class="csl-entry" role="listitem">
Rodríguez, Adrian. s.&nbsp;f. <em>Aspectos teóricos y metodológicos involucrados en el estudio de la pobreza: una revisión</em>. Instituto de Investigaciones en Ciencias Económicas. <a href="https://doi.org/10.18235/0011833">https://doi.org/10.18235/0011833</a>.
</div>
<div id="ref-Sanchez" class="csl-entry" role="listitem">
Sánchez, Carmen. 2015. <span>«Evaluación de impacto de la educación sobre la pobreza en Costa Rica (un análisis para educación secundaria y post-secundaria)»</span>. <em>Revista de Ciencias Económicas</em> 33 (2): 09-23. <a href="https://doi.org/10.15517/rce.v33i2.22608">https://doi.org/10.15517/rce.v33i2.22608</a>.
</div>
<div id="ref-Hernandez" class="csl-entry" role="listitem">
Sánchez, Leonardo, y Rafael Arias. s.&nbsp;f. <span>«Principales conclusiones del <span>Libro</span>: <span>Educación</span>, pobreza y desigualdad en <span>Costa</span> <span>Rica</span>»</span>. <a href="https://surcosdigital.com/wp-content/uploads/2017/09/Principales-conclusiones-del-libro-por-capitulo.pdf">https://surcosdigital.com/wp-content/uploads/2017/09/Principales-conclusiones-del-libro-por-capitulo.pdf</a>.
</div>
</div>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiado");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiado");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./bitacora-1.html" class="pagination-link" aria-label="Bitácora 1">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Bitácora 1</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./bitacora-3.html" class="pagination-link" aria-label="Bitácora 3">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Bitácora 3</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>